#!/usr/bin/env python3
# Levels every factory preset: runs `SmokeTest --loudness`, then writes Source/PresetTrims.h with the
# master volume that brings each preset's loudest 100 ms to the target for its category.
import subprocess, sys, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
exe = os.path.join(root, "build/SmokeTest_artefacts/Release/SmokeTest")
out = subprocess.run([exe, "--loudness"], capture_output=True, text=True, check=True).stdout
targets = {"Lead": -12.5, "House Stabs": -12.5, "Techno & Euro": -12.0, "Soundscape": -14.5, "FX": -14.0}
rows = []
for line in out.strip().splitlines():
    name, cat, db = line.split("\t")
    db = float(db)
    target = targets.get(cat, -10.0)
    vol = max(-30.0, min(12.0, target - db)) if db > -90 else -6.0
    rows.append((name, round(vol, 1), db))
with open(os.path.join(root, "Source/PresetTrims.h"), "w") as f:
    f.write("#pragma once\n\n// Generated by scripts/level_presets.py: master volume (dB) per factory preset so they all sit at\n")
    f.write("// the same loudness. Regenerate after changing presets.\n#include <map>\n#include <string>\n\nnamespace ab\n{\n")
    f.write("inline float presetTrim (const std::string& name)\n{\n    static const std::map<std::string, float> trims\n    {\n")
    for name, vol, _ in rows:
        f.write('        { "%s", %.1ff },\n' % (name.replace('"', '\\"'), vol))
    f.write("    };\n    auto it = trims.find (name);\n    return it != trims.end() ? it->second : -6.0f;\n}\n}\n")
for name, vol, db in sorted(rows, key=lambda r: r[1])[:5] + sorted(rows, key=lambda r: r[1])[-5:]:
    print(f"{name:24s} measured {db:6.1f} dB -> volume {vol:+.1f}")
print(len(rows), "presets levelled")
