#pragma once

// Everything that isn't bass: keys, plucks, pads, strings and brass, bells, voices, arps, synth drums,
// cinematic, retro, folk instruments and experimental. Appended after the original bank so existing program numbers never move.
// Same index cheat sheet as Presets.h.
namespace ab
{

inline std::vector<Preset> morePresets()
{
    // FM building block: Osc A = carrier (Rich Sine), Osc B = near-silent modulator whose octave/semi set the
    // ratio, mod env drives the FM index. Classic DX-style keys and bells.
    static const PresetValues fm
    {
        { "aTable", 12 }, { "aPos", 0.15f }, { "aWarp", 6 }, { "aWarpAmt", 0.04f },
        { "bOn", 1 }, { "bTable", 0 }, { "bPos", 0 }, { "bLevel", 0.001f }, { "bFilter", 0 },
        { "mode", 0 }, { "velSens", 0.7f }, { "fltOn", 0 },
        { "ampA", 0.002f }, { "ampD", 2.0f }, { "ampS", 0.0f }, { "ampR", 0.6f },
        { "modA", 0.001f }, { "modD", 0.5f }, { "modS", 0 }, { "modR", 0.4f },
        { "mod1Src", 3 }, { "mod1Dest", 3 }, { "mod1Amt", 0.25f },
        { "mod2Src", 4 }, { "mod2Dest", 3 }, { "mod2Amt", 0.1f },
        { "mod3Src", 7 }, { "mod3Dest", 3 }, { "mod3Amt", 0.3f },
        { "mod4Src", 10 }, { "mod4Dest", 23 }, { "mod4Amt", 0.5f },
        { "verbSize", 0.5f }, { "verbMix", 0.15f },
    };
    static const Macros mFm { "TINE", "MACRO 2", "MACRO 3", "SPACE" };

    // Subtractive poly: saw/pulse through a filter with its own envelope.
    static const PresetValues poly
    {
        { "mode", 0 }, { "velSens", 0.6f }, { "retrig", 0 },
        { "ampA", 0.003f }, { "ampD", 0.8f }, { "ampS", 0.6f }, { "ampR", 0.4f },
        { "fltType", 1 }, { "cutoff", 1800 }, { "res", 0.15f }, { "fltEnv", 0.3f }, { "fltKey", 0.4f },
        { "modA", 0.002f }, { "modD", 0.4f }, { "modS", 0.2f }, { "modR", 0.4f },
        { "mod1Src", 7 }, { "mod1Dest", 8 }, { "mod1Amt", 0.6f },
        { "mod2Src", 4 }, { "mod2Dest", 8 }, { "mod2Amt", 0.25f },
        { "mod3Src", 9 }, { "mod3Dest", 22 }, { "mod3Amt", 0.5f },
        { "mod4Src", 10 }, { "mod4Dest", 23 }, { "mod4Amt", 0.5f },
        { "verbSize", 0.55f }, { "verbMix", 0.18f },
    };
    static const Macros mPoly { "BRIGHT", "MACRO 2", "ECHO", "SPACE" };

    // Pads: slow, wide, moving.
    static const PresetValues pad
    {
        { "mode", 0 }, { "retrig", 0 }, { "velSens", 0.3f }, { "drift", 0.25f },
        { "ampA", 0.9f }, { "ampD", 3.0f }, { "ampS", 0.85f }, { "ampR", 2.5f },
        { "fltType", 0 }, { "cutoff", 2600 }, { "res", 0.12f },
        { "lfo1Rate", 0.08f }, { "lfo1Retrig", 0 }, { "lfo2Shape", 6 }, { "lfo2Rate", 0.2f }, { "lfo2Retrig", 0 },
        { "mod1Src", 1 }, { "mod1Dest", 8 }, { "mod1Amt", 0.2f },
        { "mod2Src", 2 }, { "mod2Dest", 1 }, { "mod2Amt", 0.2f },
        { "mod3Src", 7 }, { "mod3Dest", 8 }, { "mod3Amt", 0.6f },
        { "mod4Src", 10 }, { "mod4Dest", 23 }, { "mod4Amt", 0.4f },
        { "chorusMix", 0.35f }, { "verbSize", 0.8f }, { "verbMix", 0.38f }, { "width", 1.2f },
    };
    static const Macros mPad { "BLOOM", "MACRO 2", "MACRO 3", "SPACE" };

    // Synth drums: one-shots, no sustain, velocity matters.
    static const PresetValues drum
    {
        { "mode", 0 }, { "retrig", 1 }, { "velSens", 0.85f }, { "monoBass", 1 },
        { "ampA", 0.001f }, { "ampS", 0 },
        { "mod1Src", 7 }, { "mod1Dest", 19 }, { "mod1Amt", 0.6f },
        { "mod2Src", 8 }, { "mod2Dest", 23 }, { "mod2Amt", 0.5f },
    };
    static const Macros mDrum { "DIRT", "ROOM", "MACRO 3", "MACRO 4" };

    // Plucked string: a noise burst (gated by the mod env) rings a comb filter tuned to the note.
    static const PresetValues string
    {
        { "mode", 0 }, { "retrig", 1 }, { "velSens", 0.7f },
        { "aOn", 0 }, { "noiseLevel", 0.0f }, { "noiseTone", 0.9f }, { "noiseFilter", 1 },
        { "fltType", 6 }, { "cutoff", 261.6f }, { "fltKey", 1.0f }, { "res", 0.985f },
        { "ampA", 0.001f }, { "ampD", 2.0f }, { "ampS", 0 }, { "ampR", 0.4f },
        { "modA", 0.001f }, { "modD", 0.03f }, { "modS", 0 },
        { "mod1Src", 3 }, { "mod1Dest", 12 }, { "mod1Amt", 1.0f },
        { "mod2Src", 7 }, { "mod2Dest", 9 }, { "mod2Amt", 0.05f },
        { "verbSize", 0.45f }, { "verbMix", 0.15f },
    };
    static const Macros mString { "SUSTAIN", "MACRO 2", "MACRO 3", "MACRO 4" };

    auto P = [] (const char* name, const char* cat, PresetValues v, Macros m) { return Preset { name, cat, std::move (v), m }; };

    // Club studies: original synthesis recipes, no third-party samples.
    // Four deliberately assigned controls on every patch: colour, motion, echo, space.
    static const PresetValues club = {
        { "ampA", 0.003f }, { "ampD", 0.5f }, { "ampS", 0.35f }, { "ampR", 0.16f },
        { "aLevel", 0.72f }, { "velSens", 0.65f }, { "monoBass", 1 }, { "fltType", 0 }, { "cutoff", 1800 },
        { "modA", 0.002f }, { "modD", 0.18f }, { "modS", 0 }, { "modR", 0.15f },
        { "mod1Src", 7 }, { "mod1Dest", 8 }, { "mod1Amt", 0.5f },
        { "mod2Src", 8 }, { "mod2Dest", 1 }, { "mod2Amt", 0.35f },
        { "mod3Src", 9 }, { "mod3Dest", 22 }, { "mod3Amt", 0.35f },
        { "mod4Src", 10 }, { "mod4Dest", 23 }, { "mod4Amt", 0.4f },
        { "dlyTime", 5 }, { "dlyFb", 0.28f }, { "dlyTone", 0.35f }, { "verbSize", 0.5f }
    };
    static const Macros mClub { "OPEN", "COLOUR", "ECHO", "SPACE" };
    static const PresetValues clubBass = with (club, {
        { "mode", 2 }, { "glide", 0.055f }, { "aTable", 12 }, { "aPos", 0.16f },
        { "subOn", 1 }, { "subOct", 0 }, { "subLevel", 0.3f }, { "cutoff", 700 },
        { "distType", 0 }, { "distDrive", 0.18f }, { "distMix", 0.25f }, { "ampS", 0.65f }
    });
    static const PresetValues clubStab = with (club, {
        { "aTable", 0 }, { "aPos", 0.55f }, { "aUni", 2 }, { "aDetune", 0.065f },
        { "ampD", 0.28f }, { "ampS", 0 }, { "ampR", 0.18f }, { "fltEnv", 0.28f },
        { "chord", 9 }, { "chorusMix", 0.16f }, { "dlyMix", 0.12f }, { "verbMix", 0.12f }
    });
    static const PresetValues clubHit = with (club, {
        { "aTable", 12 }, { "aPos", 0.06f }, { "ampD", 0.15f }, { "ampS", 0 }, { "ampR", 0.08f },
        { "dropAmt", 12 }, { "dropTime", 0.018f }, { "velSens", 0.85f }, { "cutoff", 9000 },
        { "mod1Dest", 19 }, { "mod1Amt", 0.4f }, { "distDrive", 0.25f }
    });
    static const PresetValues clubAir = with (club, {
        { "aTable", 14 }, { "aPos", 0.3f }, { "aUni", 3 }, { "aDetune", 0.12f },
        { "ampA", 0.15f }, { "ampD", 2 }, { "ampS", 0.65f }, { "ampR", 1.5f },
        { "lfo1Rate", 0.16f }, { "lfo1Retrig", 0 }, { "mod5Src", 1 }, { "mod5Dest", 1 }, { "mod5Amt", 0.22f },
        { "verbMix", 0.3f }, { "verbSize", 0.8f }, { "dlyStyle", 2 }, { "dlyMix", 0.1f }
    });

    // Donk: the hard house / bounce / scouse bass. A two-operator FM "bonk": sine carrier (Osc A, FM warp),
    // a silent sine modulator (Osc B) at 1:1 whose depth jumps up and dies away in under 0.1 s, a quick
    // sharp-to-flat pitch blip, then short decay. Index peaks around 2.5-4 and settles near 0.7: bright enough
    // to knock, round enough to stay a bass. Macro 1 BONK (FM depth), 2 TONE (cutoff), 3 DIRT, 4 SPACE.
    static const PresetValues donk
    {
        { "mode", 1 }, { "retrig", 1 }, { "velSens", 0.35f },
        { "aTable", 0 }, { "aPos", 0.0f }, { "aWarp", 6 }, { "aWarpAmt", 0.07f }, { "aLevel", 0.9f },
        { "bOn", 1 }, { "bTable", 0 }, { "bPos", 0.0f }, { "bLevel", 0.001f }, { "bFilter", 0 },
        { "ampA", 0.001f }, { "ampD", 0.24f }, { "ampS", 0.0f }, { "ampR", 0.07f },
        { "modA", 0.001f }, { "modD", 0.075f }, { "modS", 0.0f }, { "modR", 0.05f },
        { "mod1Src", 3 }, { "mod1Dest", 3 }, { "mod1Amt", 0.38f },
        { "mod2Src", 7 }, { "mod2Dest", 3 }, { "mod2Amt", 0.18f },
        { "mod3Src", 8 }, { "mod3Dest", 8 }, { "mod3Amt", 0.4f },
        { "mod4Src", 9 }, { "mod4Dest", 19 }, { "mod4Amt", 0.5f },
        { "mod5Src", 10 }, { "mod5Dest", 23 }, { "mod5Amt", 0.4f },
        { "dropAmt", 6 }, { "dropTime", 0.016f },
        { "fltOn", 1 }, { "fltType", 1 }, { "cutoff", 4200 }, { "res", 0.1f },
        { "distType", 0 }, { "distDrive", 0.25f }, { "distMix", 0.2f },
        { "verbMode", 3 }, { "verbSize", 0.35f }, { "verbMix", 0.07f },
    };
    static const Macros mDonk { "BONK", "TONE", "DIRT", "SPACE" };

    return {
        //================================================================ Keys
        P ("FM Rhodes", "Keys", with (fm, { { "chorusMix", 0.25f }, { "lfo1Rate", 4.5f }, { "lfo1Retrig", 0 },
            { "mod5Src", 1 }, { "mod5Dest", 15 }, { "mod5Amt", 0.25f } }), mFm),
        P ("Suitcase EP", "Keys", with (fm, { { "aPos", 0.2f }, { "mod1Amt", 0.32f }, { "lfo1Rate", 4.0f }, { "lfo1Retrig", 0 },
            { "mod5Src", 1 }, { "mod5Dest", 16 }, { "mod5Amt", -0.25f }, { "distType", 0 }, { "distDrive", 0.2f }, { "distMix", 0.3f } }), mFm),
        P ("Wurli Bite", "Keys", with (fm, { { "aPos", 0.5f }, { "mod1Amt", 0.4f }, { "modD", 0.25f }, { "ampD", 1.4f },
            { "distType", 0 }, { "distDrive", 0.35f }, { "distMix", 0.5f } }), mFm),
        P ("Dream EP", "Keys", with (fm, { { "chorusMix", 0.45f }, { "verbMix", 0.35f }, { "verbShimmer", 0.25f }, { "dlyTime", 5 }, { "dlyMix", 0.15f } }), mFm),
        P ("DX Piano", "Keys", with (fm, { { "bOct", 2 }, { "aWarpAmt", 0.02f }, { "mod1Amt", 0.35f }, { "modD", 0.3f }, { "ampD", 2.5f } }), mFm),
        P ("Bright House Piano", "Keys", with (fm, { { "aPos", 0.6f }, { "aWarpAmt", 0.08f }, { "mod1Amt", 0.45f }, { "modD", 0.35f }, { "ampD", 1.2f },
            { "verbMix", 0.2f }, { "ott", 0.25f } }), mFm),
        P ("Upright Keys", "Keys", with (fm, { { "aTable", 9 }, { "aPos", 0.15f }, { "mod1Amt", 0.2f }, { "ampD", 1.8f }, { "fltOn", 1 }, { "fltType", 0 }, { "cutoff", 3500 } }), mFm),
        P ("Drawbar Organ", "Keys", with (poly, { { "aTable", 9 }, { "aPos", 0.0f }, { "bOn", 1 }, { "bTable", 9 }, { "bPos", 0.25f }, { "bOct", 1 }, { "bLevel", 0.5f },
            { "ampA", 0.004f }, { "ampS", 1.0f }, { "ampR", 0.08f }, { "fltType", 0 }, { "cutoff", 6000 }, { "fltEnv", 0 },
            { "lfo1Rate", 6.5f }, { "lfo1Retrig", 0 }, { "mod5Src", 1 }, { "mod5Dest", 15 }, { "mod5Amt", 0.35f }, { "chorusMix", 0.35f } }), mPoly),
        P ("Church Organ", "Keys", with (poly, { { "aTable", 9 }, { "aPos", 0.45f }, { "aUni", 3 }, { "aDetune", 0.05f },
            { "bOn", 1 }, { "bTable", 9 }, { "bPos", 0.1f }, { "bOct", -1 }, { "bLevel", 0.5f },
            { "ampA", 0.08f }, { "ampS", 1.0f }, { "ampR", 1.2f }, { "fltType", 0 }, { "cutoff", 5000 }, { "fltEnv", 0 },
            { "verbSize", 0.95f }, { "verbMix", 0.5f } }), mPoly),
        P ("Clavinet", "Keys", with (poly, { { "aTable", 2 }, { "aPos", 0.35f }, { "ampD", 0.5f }, { "ampS", 0.1f }, { "ampR", 0.05f },
            { "fltType", 3 }, { "cutoff", 1400 }, { "res", 0.3f }, { "fltEnv", 0.45f }, { "modD", 0.12f }, { "modS", 0 },
            { "mod2Amt", 0.4f }, { "distType", 0 }, { "distDrive", 0.25f }, { "distMix", 0.4f } }), mPoly),
        P ("Harpsichord", "Keys", with (poly, { { "aTable", 2 }, { "aPos", 0.45f }, { "bOn", 1 }, { "bTable", 1 }, { "bPos", 0.4f }, { "bOct", 1 }, { "bLevel", 0.3f },
            { "ampD", 1.2f }, { "ampS", 0 }, { "ampR", 0.3f }, { "fltType", 2 }, { "cutoff", 400 }, { "fltEnv", 0 } }), mPoly),
        P ("Celeste", "Keys", with (fm, { { "bOct", 2 }, { "aPos", 0.05f }, { "mod1Amt", 0.18f }, { "ampD", 1.6f }, { "verbMix", 0.25f } }), mFm),
        P ("Toy Piano", "Keys", with (fm, { { "aTable", 10 }, { "aPos", 0.2f }, { "bOct", 2 }, { "bSemi", 3 }, { "mod1Amt", 0.25f }, { "ampD", 0.9f } }), mFm),
        P ("Vapor Keys", "Keys", with (fm, { { "chorusMix", 0.5f }, { "drift", 0.45f }, { "distType", 5 }, { "distDrive", 0.2f }, { "distMix", 0.35f },
            { "fltOn", 1 }, { "fltType", 0 }, { "cutoff", 2400 }, { "verbMix", 0.3f } }), mFm),

        //================================================================ Plucks
        P ("Future Pluck", "Plucks", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 5 }, { "aDetune", 0.22f }, { "ampD", 0.35f }, { "ampS", 0 },
            { "cutoff", 700 }, { "fltEnv", 0.55f }, { "modD", 0.22f }, { "modS", 0 }, { "dlyTime", 5 }, { "dlyFb", 0.35f }, { "dlyMix", 0.18f } }), mPoly),
        P ("Glass Pluck", "Plucks", with (poly, { { "aTable", 13 }, { "aPos", 0.35f }, { "ampD", 0.6f }, { "ampS", 0 }, { "fltType", 0 }, { "cutoff", 5000 }, { "fltEnv", 0 },
            { "verbShimmer", 0.3f }, { "verbMix", 0.3f } }), mPoly),
        P ("Harp Pluck", "Plucks", with (fm, { { "aPos", 0.3f }, { "mod1Amt", 0.12f }, { "ampD", 1.8f }, { "fltOn", 1 }, { "fltType", 2 }, { "cutoff", 180 } }), mFm),
        P ("Tropical Pluck", "Plucks", with (poly, { { "aTable", 0 }, { "aPos", 0.2f }, { "ampD", 0.22f }, { "ampS", 0 }, { "fltType", 0 }, { "cutoff", 3000 }, { "fltEnv", 0.2f },
            { "dlyTime", 5 }, { "dlyFb", 0.4f }, { "dlyMix", 0.25f } }), mPoly),
        P ("Plucked String", "Plucks", with (string, {}), mString),
        P ("Nylon String", "Plucks", with (string, { { "res", 0.975f }, { "noiseTone", 0.6f }, { "ampD", 1.4f } }), mString),
        P ("Steel String", "Plucks", with (string, { { "res", 0.992f }, { "noiseTone", 1.0f }, { "ampD", 3.0f }, { "chorusMix", 0.15f } }), mString),
        P ("Muted Guitar", "Plucks", with (string, { { "res", 0.93f }, { "ampD", 0.25f }, { "ampR", 0.08f }, { "noiseTone", 0.5f } }), mString),
        P ("Water Drop", "Plucks", with (poly, { { "aTable", 0 }, { "aPos", 0 }, { "dropAmt", -14 }, { "dropTime", 0.06f }, { "ampD", 0.25f }, { "ampS", 0 },
            { "fltOn", 0 }, { "verbMix", 0.3f }, { "dlyTime", 3 }, { "dlyMix", 0.2f } }), mPoly),
        P ("Bubble Pluck", "Plucks", with (poly, { { "aTable", 6 }, { "aPos", 0.9f }, { "ampD", 0.2f }, { "ampS", 0 }, { "fltType", 3 }, { "cutoff", 400 }, { "res", 0.6f },
            { "fltEnv", 0.6f }, { "modD", 0.1f }, { "modS", 0 } }), mPoly),
        P ("Pizzicato", "Plucks", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 3 }, { "aDetune", 0.1f }, { "ampD", 0.3f }, { "ampS", 0 },
            { "cutoff", 1200 }, { "fltEnv", 0.3f }, { "modD", 0.15f }, { "modS", 0 }, { "verbMix", 0.3f } }), mPoly),
        P ("Mallet Pluck", "Plucks", with (fm, { { "bOct", 2 }, { "mod1Amt", 0.3f }, { "modD", 0.08f }, { "ampD", 0.5f } }), mFm),

        //================================================================ Pads
        P ("Warm Analog Pad", "Pads", with (pad, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 5 }, { "aDetune", 0.2f },
            { "bOn", 1 }, { "bTable", 2 }, { "bPos", 0.2f }, { "bLevel", 0.35f }, { "cutoff", 1600 } }), mPad),
        P ("Glass Pad", "Pads", with (pad, { { "aTable", 13 }, { "aPos", 0.5f }, { "aUni", 3 }, { "aDetune", 0.1f }, { "cutoff", 6000 }, { "verbShimmer", 0.35f } }), mPad),
        P ("Choir Pad", "Pads", with (pad, { { "aTable", 6 }, { "aPos", 0.2f }, { "aUni", 5 }, { "aDetune", 0.15f }, { "cutoff", 3500 } }), mPad),
        P ("Evolving Air", "Pads", with (pad, { { "aTable", 14 }, { "aPos", 0.3f }, { "aUni", 7 }, { "aDetune", 0.2f }, { "lfo2Rate", 0.05f }, { "mod2Amt", 0.5f } }), mPad),
        P ("Dark Pad", "Pads", with (pad, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 5 }, { "aDetune", 0.15f }, { "aOct", -1 },
            { "fltType", 1 }, { "cutoff", 600 }, { "res", 0.25f } }), mPad),
        P ("Sweep Pad", "Pads", with (pad, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.25f }, { "fltType", 1 }, { "cutoff", 500 }, { "res", 0.35f },
            { "lfo1Shape", 1 }, { "lfo1Sync", 2 }, { "mod1Amt", 0.6f } }), mPad),
        P ("Detroit Pad", "Pads", with (pad, { { "aTable", 2 }, { "aPos", 0.15f }, { "aUni", 3 }, { "aDetune", 0.12f }, { "cutoff", 2000 },
            { "dlyTime", 5 }, { "dlyFb", 0.45f }, { "dlyMix", 0.2f } }), mPad),
        P ("Lo-Fi Tape Pad", "Pads", with (pad, { { "aTable", 0 }, { "aPos", 0.4f }, { "aUni", 3 }, { "drift", 0.7f }, { "cutoff", 1800 },
            { "distType", 5 }, { "distDrive", 0.25f }, { "distMix", 0.35f }, { "chorusMix", 0.5f } }), mPad),
        P ("Ambient Swell", "Pads", with (pad, { { "aTable", 9 }, { "aPos", 0.5f }, { "aUni", 5 }, { "ampA", 2.5f }, { "ampR", 4.0f }, { "verbMix", 0.55f }, { "verbShimmer", 0.3f } }), mPad),
        P ("String Pad", "Pads", with (pad, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.18f }, { "ampA", 0.4f }, { "cutoff", 3200 },
            { "lfo2Shape", 0 }, { "lfo2Rate", 5.0f }, { "lfo2Fade", 1.0f }, { "mod2Dest", 7 }, { "mod2Amt", 0.008f } }), mPad),
        P ("Motion Pad", "Pads", with (pad, { { "aTable", 5 }, { "aPos", 0.2f }, { "aUni", 5 }, { "lfo1Shape", 0 }, { "lfo1Sync", 4 }, { "mod1Dest", 1 }, { "mod1Amt", 0.35f } }), mPad),
        P ("Ethereal Pad", "Pads", with (pad, { { "aTable", 13 }, { "aPos", 0.7f }, { "aUni", 5 }, { "bOn", 1 }, { "bTable", 14 }, { "bPos", 0.5f }, { "bOct", 1 }, { "bLevel", 0.3f },
            { "cutoff", 7000 }, { "verbShimmer", 0.6f }, { "verbMix", 0.5f } }), mPad),

        //================================================================ Strings & Brass
        P ("Synth Strings", "Strings & Brass", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.18f }, { "ampA", 0.25f }, { "ampS", 0.9f },
            { "ampR", 0.8f }, { "fltType", 0 }, { "cutoff", 4000 }, { "fltEnv", 0 }, { "lfo2Rate", 5.2f }, { "lfo2Fade", 0.6f },
            { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.008f }, { "chorusMix", 0.4f }, { "verbMix", 0.3f } }), mPoly),
        P ("Ensemble Strings", "Strings & Brass", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.28f }, { "bOn", 1 }, { "bTable", 0 },
            { "bPos", 0.66f }, { "bOct", 1 }, { "bUni", 5 }, { "bLevel", 0.3f }, { "ampA", 0.35f }, { "ampS", 0.9f }, { "ampR", 1.0f },
            { "fltType", 0 }, { "cutoff", 3000 }, { "fltEnv", 0 }, { "chorusMix", 0.6f }, { "verbMix", 0.35f } }), mPoly),
        P ("Cello Solo", "Strings & Brass", with (poly, { { "mode", 2 }, { "glide", 0.06f }, { "aTable", 0 }, { "aPos", 0.66f }, { "ampA", 0.12f }, { "ampS", 0.9f },
            { "fltType", 3 }, { "cutoff", 900 }, { "res", 0.2f }, { "fltEnv", 0 }, { "lfo2Rate", 5.0f }, { "lfo2Fade", 0.5f },
            { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.012f }, { "verbMix", 0.3f } }), mPoly),
        P ("Brass Stab", "Strings & Brass", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 3 }, { "aDetune", 0.1f }, { "ampA", 0.02f }, { "ampD", 0.5f }, { "ampS", 0.6f },
            { "cutoff", 900 }, { "fltEnv", 0.45f }, { "modA", 0.05f }, { "modD", 0.4f }, { "modS", 0.4f } }), mPoly),
        P ("Horn Section", "Strings & Brass", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 5 }, { "aDetune", 0.12f }, { "ampA", 0.06f }, { "ampS", 0.85f },
            { "cutoff", 1200 }, { "fltEnv", 0.35f }, { "modA", 0.08f }, { "modD", 0.6f }, { "modS", 0.5f }, { "chorusMix", 0.3f } }), mPoly),
        P ("Trumpet Lead", "Strings & Brass", with (poly, { { "mode", 2 }, { "glide", 0.04f }, { "aTable", 0 }, { "aPos", 0.66f }, { "ampA", 0.03f }, { "ampS", 0.9f },
            { "fltType", 3 }, { "cutoff", 1400 }, { "res", 0.3f }, { "fltEnv", 0.3f }, { "modA", 0.04f }, { "modD", 0.3f }, { "modS", 0.5f },
            { "lfo2Rate", 5.5f }, { "lfo2Fade", 0.4f }, { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.012f } }), mPoly),
        P ("Sax Lead", "Strings & Brass", with (poly, { { "mode", 2 }, { "glide", 0.05f }, { "aTable", 6 }, { "aPos", 0.3f }, { "noiseLevel", 0.06f },
            { "ampA", 0.03f }, { "ampS", 0.9f }, { "fltType", 7 }, { "cutoff", 400 }, { "res", 0.4f }, { "fltEnv", 0.25f }, { "modD", 0.4f },
            { "lfo2Rate", 5.0f }, { "lfo2Fade", 0.5f }, { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.015f } }), mPoly),
        P ("Flute", "Strings & Brass", with (poly, { { "mode", 2 }, { "glide", 0.04f }, { "aTable", 0 }, { "aPos", 0.05f }, { "noiseLevel", 0.12f }, { "noiseTone", 0.8f },
            { "ampA", 0.06f }, { "ampS", 0.9f }, { "fltType", 0 }, { "cutoff", 4000 }, { "fltEnv", 0 },
            { "lfo2Rate", 5.0f }, { "lfo2Fade", 0.6f }, { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.01f } }), mPoly),
        P ("Oboe", "Strings & Brass", with (poly, { { "mode", 2 }, { "aTable", 2 }, { "aPos", 0.7f }, { "ampA", 0.04f }, { "ampS", 0.9f },
            { "fltType", 3 }, { "cutoff", 1200 }, { "res", 0.35f }, { "fltEnv", 0 }, { "lfo2Rate", 5.2f }, { "lfo2Fade", 0.5f },
            { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.01f } }), mPoly),
        P ("Epic Strings", "Strings & Brass", with (poly, { { "chord", 3 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.2f }, { "ampA", 0.5f },
            { "ampS", 0.9f }, { "ampR", 1.5f }, { "fltType", 0 }, { "cutoff", 3500 }, { "fltEnv", 0 }, { "verbSize", 0.85f }, { "verbMix", 0.4f } }), mPoly),

        //================================================================ Bells & Mallets
        P ("Tubular Bell", "Bells & Mallets", with (fm, { { "bOct", 1 }, { "bSemi", 6 }, { "mod1Amt", 0.35f }, { "modD", 1.2f }, { "ampD", 5.0f }, { "ampR", 3.0f } }), mFm),
        P ("Music Box", "Bells & Mallets", with (fm, { { "bOct", 2 }, { "mod1Amt", 0.15f }, { "modD", 0.2f }, { "ampD", 1.8f }, { "verbMix", 0.3f } }), mFm),
        P ("Glockenspiel", "Bells & Mallets", with (fm, { { "aOct", 1 }, { "bOct", 3 }, { "bSemi", 5 }, { "mod1Amt", 0.25f }, { "modD", 0.15f }, { "ampD", 2.2f } }), mFm),
        P ("Vibraphone", "Bells & Mallets", with (fm, { { "bOct", 2 }, { "mod1Amt", 0.2f }, { "modD", 0.2f }, { "ampD", 3.0f }, { "lfo1Rate", 5.5f }, { "lfo1Retrig", 0 },
            { "mod5Src", 1 }, { "mod5Dest", 16 }, { "mod5Amt", -0.3f } }), mFm),
        P ("Marimba", "Bells & Mallets", with (fm, { { "bOct", 2 }, { "mod1Amt", 0.45f }, { "modD", 0.04f }, { "ampD", 0.6f }, { "ampR", 0.2f } }), mFm),
        P ("Crystal Bell", "Bells & Mallets", with (fm, { { "aTable", 13 }, { "aPos", 0.4f }, { "bOct", 1 }, { "bSemi", 9 }, { "mod1Amt", 0.3f }, { "ampD", 3.0f },
            { "verbShimmer", 0.4f }, { "verbMix", 0.3f } }), mFm),
        P ("Temple Bell", "Bells & Mallets", with (fm, { { "aTable", 10 }, { "aPos", 0.3f }, { "aOct", -1 }, { "bOct", 1 }, { "bSemi", 2 }, { "mod1Amt", 0.4f },
            { "modD", 2.0f }, { "ampD", 7.0f }, { "ampR", 4.0f }, { "verbMix", 0.35f } }), mFm),
        P ("Chime", "Bells & Mallets", with (fm, { { "aTable", 13 }, { "aPos", 0.7f }, { "aOct", 1 }, { "mod1Amt", 0.1f }, { "ampD", 2.5f } }), mFm),
        P ("Steel Drum", "Bells & Mallets", with (fm, { { "bSemi", 7 }, { "bOct", 1 }, { "mod1Amt", 0.3f }, { "modD", 0.12f }, { "ampD", 0.9f } }), mFm),
        P ("Kalimba", "Bells & Mallets", with (fm, { { "bOct", 3 }, { "mod1Amt", 0.35f }, { "modD", 0.03f }, { "ampD", 0.9f }, { "ampR", 0.3f } }), mFm),

        //================================================================ Vocal & Choir
        P ("Ahh Choir", "Vocal & Choir", with (pad, { { "aTable", 6 }, { "aPos", 0.0f }, { "aUni", 7 }, { "aDetune", 0.15f }, { "ampA", 0.35f }, { "cutoff", 4000 } }), mPad),
        P ("Ooh Choir", "Vocal & Choir", with (pad, { { "aTable", 6 }, { "aPos", 0.95f }, { "aUni", 7 }, { "aDetune", 0.15f }, { "ampA", 0.35f }, { "cutoff", 2500 } }), mPad),
        P ("Formant Lead", "Vocal & Choir", with (poly, { { "mode", 2 }, { "glide", 0.06f }, { "aTable", 0 }, { "aPos", 0.66f }, { "ampS", 0.9f },
            { "fltType", 7 }, { "cutoff", 300 }, { "res", 0.55f }, { "fltEnv", 0 }, { "lfo1Rate", 0.6f }, { "lfo1Retrig", 0 },
            { "mod5Src", 1 }, { "mod5Dest", 8 }, { "mod5Amt", 0.5f } }), mPoly),
        P ("Talkbox Lead", "Vocal & Choir", with (poly, { { "mode", 2 }, { "glide", 0.05f }, { "aTable", 0 }, { "aPos", 0.66f }, { "ampS", 0.9f },
            { "fltType", 7 }, { "cutoff", 250 }, { "res", 0.6f }, { "fltEnv", 0.6f }, { "modA", 0.05f }, { "modD", 0.3f }, { "modS", 0.3f } }), mPoly),
        P ("Robot Voice", "Vocal & Choir", with (poly, { { "aTable", 6 }, { "aPos", 0.5f }, { "aWarp", 5 }, { "aWarpAmt", 0.4f }, { "ampS", 0.9f },
            { "lfo1Shape", 5 }, { "lfo1Sync", 8 }, { "mod5Src", 1 }, { "mod5Dest", 1 }, { "mod5Amt", 0.4f } }), mPoly),
        P ("Whisper Pad", "Vocal & Choir", with (pad, { { "aOn", 0 }, { "noiseLevel", 0.7f }, { "noiseTone", 0.85f }, { "fltType", 7 }, { "cutoff", 400 }, { "res", 0.7f },
            { "lfo1Rate", 0.15f }, { "mod1Amt", 0.6f } }), mPad),
        P ("Angel Choir", "Vocal & Choir", with (pad, { { "aTable", 6 }, { "aPos", 0.3f }, { "aUni", 7 }, { "aOct", 1 }, { "verbShimmer", 0.6f }, { "verbMix", 0.5f } }), mPad),
        P ("Vocoder Chords", "Vocal & Choir", with (poly, { { "chord", 9 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 3 }, { "ampA", 0.05f }, { "ampS", 0.8f },
            { "fltType", 7 }, { "cutoff", 350 }, { "res", 0.5f }, { "fltEnv", 0 }, { "lfo1Sync", 5 }, { "lfo1Retrig", 0 },
            { "mod5Src", 1 }, { "mod5Dest", 8 }, { "mod5Amt", 0.4f } }), mPoly),

        //================================================================ Arps
        P ("Up Arp Pluck", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 0 }, { "arpRate", 3 }, { "arpOct", 2 }, { "arpGate", 0.5f },
            { "aTable", 0 }, { "aPos", 0.66f }, { "ampD", 0.2f }, { "ampS", 0 }, { "cutoff", 1000 }, { "fltEnv", 0.45f }, { "modD", 0.15f }, { "modS", 0 },
            { "dlyTime", 5 }, { "dlyMix", 0.15f } }), mPoly),
        P ("Bouncing Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 1 }, { "arpRate", 4 }, { "arpOct", 2 }, { "arpGate", 0.4f },
            { "aTable", 2 }, { "aPos", 0.3f }, { "ampD", 0.18f }, { "ampS", 0 }, { "cutoff", 1500 }, { "fltEnv", 0.35f }, { "modD", 0.1f } }), mPoly),
        P ("Random Glass Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 3 }, { "arpRate", 3 }, { "arpOct", 3 }, { "arpGate", 0.35f },
            { "aTable", 13 }, { "aPos", 0.4f }, { "ampD", 0.4f }, { "ampS", 0 }, { "fltType", 0 }, { "cutoff", 6000 }, { "fltEnv", 0 }, { "verbMix", 0.3f } }), mPoly),
        P ("Chord Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 2 }, { "arpRate", 3 }, { "arpOct", 1 }, { "chord", 9 },
            { "aTable", 0 }, { "aPos", 0.66f }, { "ampD", 0.25f }, { "ampS", 0 }, { "cutoff", 1400 }, { "fltEnv", 0.3f } }), mPoly),
        P ("80s Sequence", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 0 }, { "arpRate", 3 }, { "arpOct", 1 }, { "arpGate", 0.7f },
            { "aTable", 2 }, { "aPos", 0.2f }, { "ampD", 0.3f }, { "ampS", 0.3f }, { "fltType", 1 }, { "cutoff", 800 }, { "res", 0.35f }, { "fltEnv", 0.4f },
            { "modD", 0.15f }, { "chorusMix", 0.35f }, { "dlyTime", 5 }, { "dlyMix", 0.2f } }), mPoly),
        P ("Stranger Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 2 }, { "arpRate", 3 }, { "arpOct", 3 }, { "arpGate", 0.6f },
            { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 2 }, { "ampD", 0.3f }, { "ampS", 0.2f }, { "fltType", 1 }, { "cutoff", 600 }, { "res", 0.4f },
            { "fltEnv", 0.45f }, { "modD", 0.18f }, { "verbMix", 0.3f } }), mPoly),
        P ("Minimal Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 4 }, { "arpRate", 3 }, { "arpOct", 1 }, { "arpGate", 0.25f },
            { "aTable", 0 }, { "aPos", 0.0f }, { "ampD", 0.12f }, { "ampS", 0 }, { "fltOn", 0 }, { "dlyTime", 2 }, { "dlyFb", 0.45f }, { "dlyMix", 0.25f } }), mPoly),
        P ("Wooden Marimba Arp", "Arps", with (fm, { { "arpOn", 1 }, { "arpMode", 2 }, { "arpRate", 3 }, { "arpOct", 2 }, { "arpGate", 0.5f },
            { "bOct", 2 }, { "mod1Amt", 0.45f }, { "modD", 0.04f }, { "ampD", 0.5f } }), mFm),
        P ("Octave Pulse Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 0 }, { "arpRate", 3 }, { "arpOct", 2 }, { "arpGate", 0.5f },
            { "aTable", 2 }, { "aPos", 0.5f }, { "ampD", 0.2f }, { "ampS", 0.1f }, { "cutoff", 2000 }, { "fltEnv", 0.2f } }), mPoly),
        P ("Trance Arp", "Arps", with (poly, { { "arpOn", 1 }, { "arpMode", 0 }, { "arpRate", 3 }, { "arpOct", 3 }, { "arpGate", 0.6f },
            { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.3f }, { "ampD", 0.25f }, { "ampS", 0.1f },
            { "cutoff", 2000 }, { "fltEnv", 0.3f }, { "dlyTime", 5 }, { "dlyFb", 0.4f }, { "dlyMix", 0.25f }, { "verbMix", 0.3f } }), mPoly),

        //================================================================ Synth drums
        P ("909 Kick", "Synth Drums", with (drum, { { "aTable", 0 }, { "aPos", 0.05f }, { "dropAmt", 36 }, { "dropTime", 0.08f }, { "ampD", 0.45f }, { "fltOn", 0 },
            { "noiseLevel", 0.25f }, { "noiseFilter", 0 }, { "modD", 0.01f }, { "modS", 0 }, { "mod3Src", 3 }, { "mod3Dest", 12 }, { "mod3Amt", 0.4f },
            { "distType", 0 }, { "distDrive", 0.25f }, { "distMix", 0.5f } }), mDrum),
        P ("Deep Kick", "Synth Drums", with (drum, { { "aTable", 0 }, { "aPos", 0 }, { "dropAmt", 30 }, { "dropTime", 0.12f }, { "ampD", 0.9f }, { "fltOn", 0 } }), mDrum),
        P ("Hard Techno Kick", "Synth Drums", with (drum, { { "aTable", 0 }, { "aPos", 0.1f }, { "dropAmt", 40 }, { "dropTime", 0.07f }, { "ampD", 0.6f }, { "fltOn", 0 },
            { "distType", 1 }, { "distDrive", 0.6f }, { "distMix", 1 }, { "ott", 0.3f } }), mDrum),
        P ("808 Kick", "Synth Drums", with (drum, { { "aTable", 3 }, { "aPos", 0.1f }, { "dropAmt", 24 }, { "dropTime", 0.05f }, { "ampD", 1.2f }, { "fltOn", 0 } }), mDrum),
        P ("Tone Snare", "Synth Drums", with (drum, { { "aTable", 0 }, { "aPos", 0.3f }, { "aOct", 1 }, { "dropAmt", 7 }, { "dropTime", 0.03f }, { "aLevel", 0.5f },
            { "noiseLevel", 0.8f }, { "noiseTone", 0.85f }, { "noiseFilter", 1 }, { "ampD", 0.3f }, { "fltType", 2 }, { "cutoff", 200 } }), mDrum),
        P ("Noise Snare", "Synth Drums", with (drum, { { "aOn", 0 }, { "noiseLevel", 1.0f }, { "noiseTone", 0.9f }, { "ampD", 0.25f },
            { "fltType", 3 }, { "cutoff", 2500 }, { "res", 0.2f }, { "fltKey", 0 } }), mDrum),
        P ("Hand Clap", "Synth Drums", with (drum, { { "aOn", 0 }, { "noiseLevel", 1.0f }, { "noiseTone", 0.8f }, { "ampD", 0.35f },
            { "fltType", 3 }, { "cutoff", 1400 }, { "res", 0.3f }, { "lfo1Shape", 2 }, { "lfo1Rate", 28.0f }, { "lfo1Retrig", 1 }, { "lfo1Fade", 0.0f },
            { "mod3Src", 1 }, { "mod3Dest", 16 }, { "mod3Amt", 0.8f }, { "verbMix", 0.15f }, { "verbSize", 0.35f } }), mDrum),
        P ("Closed Hat", "Synth Drums", with (drum, { { "aOn", 0 }, { "noiseLevel", 1.0f }, { "noiseTone", 1.0f }, { "ampD", 0.07f }, { "ampR", 0.04f },
            { "fltType", 2 }, { "cutoff", 7000 }, { "fltKey", 0 } }), mDrum),
        P ("Open Hat", "Synth Drums", with (drum, { { "aOn", 0 }, { "noiseLevel", 1.0f }, { "noiseTone", 1.0f }, { "ampD", 0.5f }, { "ampR", 0.2f },
            { "fltType", 2 }, { "cutoff", 6500 }, { "fltKey", 0 } }), mDrum),
        P ("Synth Tom", "Synth Drums", with (drum, { { "aTable", 0 }, { "aPos", 0.05f }, { "dropAmt", 12 }, { "dropTime", 0.12f }, { "ampD", 0.6f }, { "fltOn", 0 } }), mDrum),
        P ("Rimshot", "Synth Drums", with (drum, { { "aTable", 10 }, { "aPos", 0.5f }, { "aOct", 1 }, { "ampD", 0.06f }, { "fltType", 3 }, { "cutoff", 1800 }, { "res", 0.4f } }), mDrum),
        P ("Cowbell", "Synth Drums", with (drum, { { "aTable", 2 }, { "aPos", 0.0f }, { "bOn", 1 }, { "bTable", 2 }, { "bPos", 0 }, { "bSemi", 7 }, { "bLevel", 0.6f },
            { "ampD", 0.3f }, { "fltType", 3 }, { "cutoff", 900 }, { "res", 0.3f }, { "fltKey", 1.0f } }), mDrum),
        P ("Shaker", "Synth Drums", with (drum, { { "aOn", 0 }, { "noiseLevel", 1.0f }, { "noiseTone", 1.0f }, { "ampA", 0.02f }, { "ampD", 0.12f },
            { "fltType", 2 }, { "cutoff", 5000 }, { "fltKey", 0 } }), mDrum),
        P ("Laser Perc", "Synth Drums", with (drum, { { "aTable", 2 }, { "aPos", 0.2f }, { "dropAmt", 36 }, { "dropTime", 0.05f }, { "ampD", 0.15f }, { "fltOn", 0 } }), mDrum),

        //================================================================ Cinematic
        P ("Braam", "Cinematic", with (pad, { { "aTable", 0 }, { "aPos", 0.66f }, { "aOct", -1 }, { "aUni", 7 }, { "aDetune", 0.25f },
            { "bOn", 1 }, { "bTable", 2 }, { "bPos", 0.2f }, { "bOct", -1 }, { "bLevel", 0.5f }, { "ampA", 0.05f }, { "ampD", 3.0f }, { "ampS", 0.5f },
            { "fltType", 1 }, { "cutoff", 700 }, { "fltEnv", 0.4f }, { "modA", 0.5f }, { "modD", 2.0f }, { "modS", 0.3f },
            { "distType", 0 }, { "distDrive", 0.5f }, { "distMix", 0.7f }, { "verbSize", 0.9f }, { "verbMix", 0.4f } }), mPad),
        P ("Dark Drone", "Cinematic", with (pad, { { "aTable", 6 }, { "aPos", 0.9f }, { "aOct", -1 }, { "aUni", 5 }, { "fltType", 1 }, { "cutoff", 1400 }, { "res", 0.3f },
            { "lfo1Rate", 0.03f }, { "mod1Amt", 0.5f }, { "verbShimmer", 0.1f } }), mPad),
        P ("Impact Hit", "Cinematic", with (drum, { { "aTable", 0 }, { "aPos", 0 }, { "aOct", -1 }, { "dropAmt", 24 }, { "dropTime", 0.3f }, { "ampD", 3.0f },
            { "noiseLevel", 0.4f }, { "noiseFilter", 0 }, { "fltOn", 0 }, { "distType", 0 }, { "distDrive", 0.5f }, { "distMix", 0.7f },
            { "verbSize", 0.95f }, { "verbMix", 0.45f } }), mDrum),
        P ("Sub Drop", "Cinematic", with (drum, { { "aTable", 0 }, { "aPos", 0 }, { "dropAmt", 24 }, { "dropTime", 1.0f }, { "ampD", 4.0f }, { "fltOn", 0 } }), mDrum),
        P ("Metallic Scrape", "Cinematic", with (pad, { { "aTable", 10 }, { "aPos", 0.8f }, { "fltType", 6 }, { "cutoff", 300 }, { "res", 0.85f }, { "fltKey", 0 },
            { "lfo1Shape", 6 }, { "lfo1Rate", 0.3f }, { "mod1Amt", 0.7f } }), mPad),
        P ("Horror Swell", "Cinematic", with (pad, { { "chord", 16 }, { "aTable", 6 }, { "aPos", 0.8f }, { "aUni", 5 }, { "ampA", 3.0f }, { "cutoff", 1500 },
            { "lfo2Shape", 0 }, { "lfo2Rate", 6.0f }, { "lfo2Fade", 2.0f }, { "mod2Dest", 7 }, { "mod2Amt", 0.03f } }), mPad),
        P ("Epic Pad", "Cinematic", with (pad, { { "chord", 5 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.2f },
            { "bOn", 1 }, { "bTable", 6 }, { "bPos", 0.2f }, { "bLevel", 0.35f }, { "cutoff", 3000 }, { "verbSize", 1.0f }, { "verbMix", 0.5f } }), mPad),
        P ("Tension Pulse", "Cinematic", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aOct", -1 }, { "ampS", 0.9f }, { "cutoff", 500 }, { "fltEnv", 0 },
            { "lfo1Shape", 4 }, { "lfo1Sync", 7 }, { "lfo1Retrig", 0 }, { "mod5Src", 1 }, { "mod5Dest", 16 }, { "mod5Amt", -0.7f },
            { "dlyTime", 7 }, { "dlyMix", 0.2f } }), mPoly),

        //================================================================ Retro & Chip
        P ("Chip Square Lead", "Retro & Chip", with (poly, { { "mode", 1 }, { "aTable", 7 }, { "aPos", 0.95f }, { "aWarp", 4 }, { "aWarpAmt", 0.0f }, { "ampS", 0.9f }, { "fltOn", 0 },
            { "lfo2Rate", 6.0f }, { "lfo2Fade", 0.3f }, { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.02f } }), mPoly),
        P ("Chip Arp", "Retro & Chip", with (poly, { { "arpOn", 1 }, { "arpMode", 0 }, { "arpRate", 5 }, { "arpOct", 1 }, { "chord", 4 },
            { "aTable", 2 }, { "aPos", 0.0f }, { "ampS", 0.9f }, { "fltOn", 0 }, { "distType", 5 }, { "distDrive", 0.35f }, { "distMix", 0.6f } }), mPoly),
        P ("8-Bit Pluck", "Retro & Chip", with (poly, { { "aTable", 2 }, { "aPos", 0.6f }, { "ampD", 0.2f }, { "ampS", 0 }, { "fltOn", 0 },
            { "distType", 5 }, { "distDrive", 0.5f }, { "distMix", 0.7f } }), mPoly),
        P ("NES Triangle", "Retro & Chip", with (poly, { { "mode", 1 }, { "aTable", 7 }, { "aPos", 0.6f }, { "ampS", 1.0f }, { "fltOn", 0 } }), mPoly),
        P ("Game Over", "Retro & Chip", with (poly, { { "aTable", 2 }, { "aPos", 0.0f }, { "dropAmt", -24 }, { "dropTime", 0.8f }, { "ampD", 1.0f }, { "ampS", 0 }, { "fltOn", 0 },
            { "distType", 5 }, { "distDrive", 0.4f }, { "distMix", 0.6f } }), mPoly),
        P ("Retro Laser", "Retro & Chip", with (poly, { { "aTable", 2 }, { "aPos", 0.3f }, { "dropAmt", 30 }, { "dropTime", 0.2f }, { "ampD", 0.3f }, { "ampS", 0 }, { "fltOn", 0 },
            { "dlyTime", 3 }, { "dlyMix", 0.25f } }), mPoly),
        P ("Power Up", "Retro & Chip", with (poly, { { "arpOn", 1 }, { "arpMode", 0 }, { "arpRate", 5 }, { "arpOct", 3 }, { "chord", 4 },
            { "aTable", 2 }, { "aPos", 0.2f }, { "ampS", 0.8f }, { "fltOn", 0 }, { "distType", 5 }, { "distDrive", 0.3f }, { "distMix", 0.5f } }), mPoly),
        P ("Coin", "Retro & Chip", with (poly, { { "aTable", 2 }, { "aPos", 0.0f }, { "aOct", 1 }, { "dropAmt", -5 }, { "dropTime", 0.06f }, { "ampD", 0.35f }, { "ampS", 0 },
            { "fltOn", 0 } }), mPoly),

        //================================================================ Folk Instruments
        P ("Koto", "Folk Instruments", with (string, { { "res", 0.985f }, { "noiseTone", 0.95f }, { "ampD", 1.6f }, { "bendRange", 2 }, { "verbMix", 0.25f } }), mString),
        P ("Sitar", "Folk Instruments", with (string, { { "aOn", 1 }, { "aTable", 1 }, { "aPos", 0.3f }, { "aLevel", 0.12f }, { "res", 0.99f }, { "ampD", 3.0f },
            { "chorusMix", 0.2f }, { "verbMix", 0.2f } }), mString),
        P ("Pan Flute", "Folk Instruments", with (poly, { { "mode", 2 }, { "aTable", 0 }, { "aPos", 0.12f }, { "noiseLevel", 0.25f }, { "noiseTone", 0.7f },
            { "ampA", 0.05f }, { "ampS", 0.85f }, { "fltType", 0 }, { "cutoff", 3000 }, { "fltEnv", 0 }, { "verbMix", 0.3f } }), mPoly),
        P ("Balafon", "Folk Instruments", with (fm, { { "bOct", 2 }, { "bSemi", 1 }, { "mod1Amt", 0.5f }, { "modD", 0.03f }, { "ampD", 0.45f }, { "distType", 0 }, { "distDrive", 0.2f }, { "distMix", 0.3f } }), mFm),
        P ("Guzheng", "Folk Instruments", with (string, { { "res", 0.988f }, { "noiseTone", 1.0f }, { "ampD", 2.4f }, { "mode", 2 }, { "glide", 0.08f }, { "verbMix", 0.3f } }), mString),
        P ("Oud", "Folk Instruments", with (string, { { "res", 0.975f }, { "noiseTone", 0.7f }, { "ampD", 1.2f }, { "fltEnv", 0.1f } }), mString),
        P ("Didgeridoo", "Folk Instruments", with (poly, { { "mode", 1 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aOct", -1 }, { "ampS", 1.0f },
            { "fltType", 7 }, { "cutoff", 150 }, { "res", 0.6f }, { "fltEnv", 0 }, { "lfo1Rate", 1.5f }, { "lfo1Retrig", 0 },
            { "mod5Src", 1 }, { "mod5Dest", 8 }, { "mod5Amt", 0.35f } }), mPoly),
        P ("Hang Drum", "Folk Instruments", with (fm, { { "aPos", 0.1f }, { "bOct", 1 }, { "bSemi", 7 }, { "mod1Amt", 0.15f }, { "modD", 0.1f }, { "ampD", 2.0f },
            { "verbMix", 0.3f } }), mFm),
        //================================================================ Experimental
        // Built from what producers say generic packs never have: sounds that evolve, glitch, talk, clang and break.
        P ("Glacier Engine", "Experimental", with (pad, { { "aTable", 12 }, { "aPos", 0.2f }, { "aUni", 7 }, { "aDetune", 0.12f },
            { "bOn", 1 }, { "bTable", 6 }, { "bPos", 0.5f }, { "bLevel", 0.5f }, { "ampA", 2.0f }, { "ampR", 4.0f },
            { "cutoff", 600 }, { "modA", 5.0f }, { "modD", 5.0f }, { "modS", 1.0f }, { "modR", 4.0f },
            { "lfo1Rate", 0.03f }, { "mod1Src", 1 }, { "mod1Dest", 1 }, { "mod1Amt", 0.5f },
            { "mod2Src", 1 }, { "mod2Dest", 2 }, { "mod2Amt", -0.5f }, { "mod5Src", 3 }, { "mod5Dest", 8 }, { "mod5Amt", 0.55f },
            { "verbShimmer", 0.5f }, { "verbMix", 0.5f }, { "verbSize", 0.92f }, { "chorusMix", 0.3f } }),
          { "THAW", "MACRO 2", "MACRO 3", "SPACE" }),
        P ("Tidepool", "Experimental", with (pad, { { "aTable", 12 }, { "aPos", 0.1f }, { "aLevel", 0.25f }, { "noiseLevel", 0.6f }, { "noiseTone", 0.6f },
            { "fltType", 3 }, { "cutoff", 800 }, { "res", 0.3f }, { "lfo1Shape", 6 }, { "lfo1Rate", 0.12f }, { "mod1Amt", 0.5f },
            { "lfo2Rate", 0.07f }, { "mod2Dest", 15 }, { "mod2Amt", 0.6f },
            { "dlyPing", 1 }, { "dlyTime", 8 }, { "dlyFb", 0.5f }, { "dlyTone", 0.3f }, { "dlyMix", 0.3f }, { "verbSize", 0.9f }, { "verbMix", 0.45f } }),
          { "CURRENT", "MACRO 2", "MACRO 3", "SPACE" }),
        P ("Deep Field Radio", "Experimental", with (pad, { { "aTable", 10 }, { "aPos", 0.3f }, { "aWarp", 3 }, { "aWarpAmt", 0.4f },
            { "bOn", 1 }, { "bTable", 12 }, { "bSemi", 7 }, { "bLevel", 0.4f },
            { "lfo1Shape", 5 }, { "lfo1Rate", 3.0f }, { "mod1Dest", 1 }, { "mod1Amt", 0.4f },
            { "fltType", 6 }, { "cutoff", 200 }, { "fltKey", 1.0f }, { "res", 0.6f }, { "fltMix", 0.6f },
            { "verbShimmer", 0.4f }, { "verbMix", 0.45f } }),
          { "TUNE IN", "MACRO 2", "MACRO 3", "SPACE" }),
        P ("Moth Choir", "Experimental", with (pad, { { "aTable", 6 }, { "aPos", 0.3f }, { "aUni", 5 }, { "aDetune", 0.2f },
            { "bOn", 1 }, { "bTable", 6 }, { "bPos", 0.7f }, { "bLevel", 0.5f }, { "ampA", 1.2f },
            { "fltType", 7 }, { "cutoff", 800 }, { "res", 0.5f }, { "lfo1Rate", 0.05f }, { "mod1Amt", 0.5f },
            { "chorusMix", 0.4f }, { "verbMix", 0.45f }, { "verbSize", 0.85f } }),
          { "VOWEL", "MACRO 2", "MACRO 3", "SPACE" }),
        P ("Rust Bloom", "Experimental", with (pad, { { "aTable", 0 }, { "aPos", 0.66f }, { "bOn", 1 }, { "bTable", 7 }, { "bPos", 0.4f }, { "bLevel", 0.45f },
            { "aWarp", 5 }, { "aWarpAmt", 0.05f }, { "ampA", 1.5f },
            { "modA", 5.0f }, { "modD", 5.0f }, { "modS", 1.0f }, { "modR", 3.0f },
            { "mod5Src", 3 }, { "mod5Dest", 3 }, { "mod5Amt", 0.8f }, { "mod6Src", 3 }, { "mod6Dest", 19 }, { "mod6Amt", 0.6f },
            { "fltType", 4 }, { "cutoff", 900 }, { "res", 0.4f }, { "lfo1Rate", 0.1f }, { "mod1Amt", 0.4f },
            { "distType", 0 }, { "distDrive", 0.2f }, { "distMix", 0.5f } }),
          { "CORRODE", "MACRO 2", "MACRO 3", "SPACE" }),
        P ("Stutter Loom", "Experimental", with (poly, { { "arpOn", 1 }, { "arpMode", 3 }, { "arpRate", 5 }, { "arpOct", 2 }, { "arpGate", 0.4f },
            { "aTable", 7 }, { "aPos", 0.3f }, { "aWarp", 5 }, { "aWarpAmt", 0.3f }, { "ampD", 0.2f }, { "ampS", 0.3f }, { "ampR", 0.1f },
            { "lfo1Shape", 5 }, { "lfo1Sync", 8 }, { "mod5Src", 1 }, { "mod5Dest", 1 }, { "mod5Amt", 0.8f },
            { "dlyPing", 1 }, { "dlyTime", 0 }, { "dlyFb", 0.45f }, { "dlyMix", 0.25f } }), mPoly),
        P ("Chopped Signal", "Experimental", with (poly, { { "aTable", 7 }, { "aPos", 0.2f }, { "aWarp", 5 }, { "aWarpAmt", 0.5f }, { "ampS", 0.9f },
            { "lfo1Shape", 2 }, { "lfo1Sync", 9 }, { "mod5Src", 1 }, { "mod5Dest", 1 }, { "mod5Amt", 0.7f },
            { "lfo2Shape", 4 }, { "lfo2Sync", 8 }, { "mod6Src", 2 }, { "mod6Dest", 16 }, { "mod6Amt", -0.7f },
            { "dlyTime", 0 }, { "dlyFb", 0.6f }, { "dlyMix", 0.2f } }), mPoly),
        P ("Grain Rain", "Experimental", with (poly, { { "arpOn", 1 }, { "arpMode", 3 }, { "arpRate", 5 }, { "arpOct", 3 }, { "arpGate", 0.3f },
            { "aTable", 13 }, { "aPos", 0.5f }, { "bOn", 1 }, { "bTable", 10 }, { "bOct", 2 }, { "bLevel", 0.2f },
            { "ampD", 0.25f }, { "ampS", 0 }, { "fltType", 2 }, { "cutoff", 400 }, { "fltEnv", 0 },
            { "lfo1Shape", 5 }, { "lfo1Rate", 12.0f }, { "mod5Src", 1 }, { "mod5Dest", 7 }, { "mod5Amt", 0.01f },
            { "chorusMix", 0.4f }, { "verbShimmer", 0.6f }, { "verbMix", 0.45f }, { "verbSize", 0.85f } }), mPoly),
        P ("Scanner Error", "Experimental", with (poly, { { "mode", 1 }, { "glide", 0.03f }, { "aTable", 2 }, { "aPos", 0.3f }, { "aWarp", 4 }, { "aWarpAmt", 0.3f },
            { "ampS", 0.9f }, { "fltType", 3 }, { "cutoff", 1500 }, { "res", 0.5f }, { "fltEnv", 0 },
            { "lfo1Shape", 5 }, { "lfo1Sync", 8 }, { "mod5Src", 1 }, { "mod5Dest", 3 }, { "mod5Amt", 0.6f },
            { "lfo2Shape", 5 }, { "lfo2Sync", 12 }, { "mod6Src", 2 }, { "mod6Dest", 8 }, { "mod6Amt", 0.5f },
            { "dlyTime", 1 }, { "dlyMix", 0.2f } }), mPoly),
        // Mod env holds pitch +12 while the key is down and transpose pulls it back; on release it sags an octave.
        P ("Tape Stop Keys", "Experimental", with (poly, { { "aTable", 12 }, { "aPos", 0.35f }, { "transpose", -12 }, { "ampS", 0.7f }, { "ampR", 0.7f },
            { "modA", 0.001f }, { "modS", 1.0f }, { "modR", 0.7f }, { "fltType", 0 }, { "cutoff", 2500 }, { "fltEnv", 0.2f },
            { "mod5Src", 3 }, { "mod5Dest", 7 }, { "mod5Amt", 1.0f }, { "dlyTime", 5 }, { "dlyTone", 0.3f }, { "dlyMix", 0.2f } }), mPoly),
        P ("Foundry Bell", "Experimental", with (fm, { { "bOct", 1 }, { "bSemi", 10 }, { "bFine", 3 }, { "mod1Amt", 0.45f }, { "modD", 1.2f },
            { "ampD", 5.0f }, { "ampR", 3.0f }, { "verbMix", 0.35f }, { "verbSize", 0.8f } }), mFm),
        P ("Broken Glockenspiel", "Experimental", with (fm, { { "aOct", 1 }, { "bOct", 2 }, { "bSemi", 10 }, { "mod1Amt", 0.3f }, { "modD", 0.25f },
            { "ampD", 1.5f }, { "drift", 0.5f }, { "mod5Src", 11 }, { "mod5Dest", 7 }, { "mod5Amt", 0.02f }, { "aWarp", 6 },
            { "dlyTime", 5 }, { "dlyMix", 0.2f } }), mFm),
        P ("Scrap Yard Hit", "Experimental", with (drum, { { "aTable", 10 }, { "aPos", 0.5f }, { "noiseLevel", 0.6f }, { "noiseTone", 0.8f },
            { "fltType", 6 }, { "cutoff", 180 }, { "res", 0.9f }, { "fltKey", 0.5f }, { "ampD", 0.6f },
            { "dropAmt", 12 }, { "dropTime", 0.03f }, { "distType", 1 }, { "distDrive", 0.4f }, { "distMix", 0.6f } }), mDrum),
        P ("Singing Bowl", "Experimental", with (fm, { { "bOct", 1 }, { "bSemi", 4 }, { "bFine", 30 }, { "mod1Amt", 0.1f }, { "modD", 3.0f },
            { "ampD", 10.0f }, { "ampR", 6.0f }, { "lfo1Rate", 0.3f }, { "mod5Src", 1 }, { "mod5Dest", 3 }, { "mod5Amt", 0.15f },
            { "fltOn", 1 }, { "fltType", 4 }, { "cutoff", 2000 }, { "lfo2Rate", 0.05f }, { "mod6Src", 2 }, { "mod6Dest", 8 }, { "mod6Amt", 0.3f },
            { "verbShimmer", 0.3f }, { "verbMix", 0.4f } }), mFm),
        P ("Clock Tower Swarm", "Experimental", with (fm, { { "bOct", 1 }, { "bSemi", 10 }, { "bFine", 3 }, { "mod1Amt", 0.35f }, { "modD", 0.8f },
            { "chord", 11 }, { "strum", 0.05f }, { "ampD", 3.0f }, { "dlyPing", 1 }, { "dlyTime", 4 }, { "dlyFb", 0.45f }, { "dlyMix", 0.3f },
            { "verbMix", 0.3f } }), mFm),
        P ("Yoi Machine", "Experimental", with (poly, { { "mode", 2 }, { "glide", 0.06f }, { "aTable", 6 }, { "aPos", 0.3f }, { "aUni", 3 }, { "aDetune", 0.1f },
            { "ampS", 1.0f }, { "fltType", 7 }, { "cutoff", 700 }, { "res", 0.5f }, { "fltEnv", 0 },
            { "lfo1Sync", 7 }, { "mod5Src", 1 }, { "mod5Dest", 1 }, { "mod5Amt", 0.6f }, { "mod6Src", 1 }, { "mod6Dest", 8 }, { "mod6Amt", 0.6f },
            { "subOn", 1 }, { "subOct", 0 }, { "subLevel", 0.5f }, { "distType", 1 }, { "distDrive", 0.5f }, { "distMix", 0.7f } }),
          { "YOI", "MACRO 2", "ECHO", "SPACE" }),
        P ("Mouth Organ", "Experimental", with (poly, { { "mode", 2 }, { "glide", 0.08f }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 2 }, { "aDetune", 0.08f },
            { "ampS", 1.0f }, { "fltType", 7 }, { "cutoff", 500 }, { "res", 0.6f }, { "fltEnv", 0 },
            { "mod5Src", 5 }, { "mod5Dest", 8 }, { "mod5Amt", 0.8f }, { "lfo2Rate", 5.0f }, { "lfo2Fade", 0.4f },
            { "mod6Src", 2 }, { "mod6Dest", 7 }, { "mod6Amt", 0.015f } }),
          { "BRIGHT", "MACRO 2", "ECHO", "SPACE" }),
        P ("Robot Gossip", "Experimental", with (poly, { { "mode", 1 }, { "aTable", 6 }, { "aPos", 0.5f }, { "aWarp", 5 }, { "aWarpAmt", 0.4f }, { "ampS", 1.0f },
            { "fltType", 7 }, { "cutoff", 900 }, { "res", 0.5f }, { "fltEnv", 0 },
            { "lfo1Shape", 5 }, { "lfo1Sync", 8 }, { "mod5Src", 1 }, { "mod5Dest", 8 }, { "mod5Amt", 0.7f },
            { "lfo2Shape", 5 }, { "lfo2Sync", 8 }, { "mod6Src", 2 }, { "mod6Dest", 7 }, { "mod6Amt", 0.17f } }), mPoly),
        P ("Ghost Choir Stab", "Experimental", with (poly, { { "chord", 15 }, { "aTable", 6 }, { "aPos", 0.5f }, { "aUni", 4 }, { "aDetune", 0.2f },
            { "ampD", 0.8f }, { "ampS", 0 }, { "ampR", 0.6f }, { "fltType", 7 }, { "cutoff", 1200 }, { "res", 0.4f }, { "fltEnv", -0.4f }, { "modD", 0.3f },
            { "verbMix", 0.5f }, { "verbSize", 0.9f } }), mPoly),
        P ("Arguing Machines", "Experimental", with (poly, { { "mode", 1 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 2 }, { "aDetune", 0.15f },
            { "bOn", 1 }, { "bTable", 5 }, { "bLevel", 0.6f }, { "aWarp", 6 }, { "aWarpAmt", 0.3f }, { "ampS", 1.0f },
            { "lfo1Sync", 11 }, { "mod5Src", 1 }, { "mod5Dest", 3 }, { "mod5Amt", 0.5f },
            { "lfo2Shape", 5 }, { "lfo2Sync", 8 }, { "mod6Src", 2 }, { "mod6Dest", 2 }, { "mod6Amt", 0.6f },
            { "fltType", 6 }, { "cutoff", 300 }, { "res", 0.6f }, { "fltMix", 0.5f }, { "fltEnv", 0 },
            { "subOn", 1 }, { "subOct", 0 }, { "subLevel", 0.5f }, { "distType", 1 }, { "distDrive", 0.5f }, { "distMix", 0.8f }, { "eqLow", 3.0f } }),
          { "ARGUE", "MACRO 2", "ECHO", "SPACE" }),
        P ("Tectonic Reese", "Experimental", with (poly, { { "mode", 1 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.25f },
            { "bOn", 1 }, { "bTable", 0 }, { "bPos", 0.66f }, { "bUni", 7 }, { "bDetune", 0.3f }, { "bFine", 7 }, { "ampS", 1.0f },
            { "lfo1Rate", 0.15f }, { "lfo1Retrig", 0 }, { "mod5Src", 1 }, { "mod5Dest", 13 }, { "mod5Amt", 0.4f },
            { "fltType", 1 }, { "cutoff", 500 }, { "fltEnv", 0 }, { "subOn", 1 }, { "subOct", 0 }, { "subLevel", 0.6f }, { "monoBass", 1 } }),
          { "OPEN", "MACRO 2", "ECHO", "SPACE" }),
        P ("Sync Snarl", "Experimental", with (poly, { { "mode", 1 }, { "aTable", 1 }, { "aPos", 0.4f }, { "aWarp", 1 }, { "aWarpAmt", 0.3f }, { "ampS", 1.0f },
            { "modD", 0.4f }, { "mod5Src", 3 }, { "mod5Dest", 3 }, { "mod5Amt", 0.5f },
            { "lfo1Sync", 11 }, { "mod6Src", 1 }, { "mod6Dest", 3 }, { "mod6Amt", 0.3f },
            { "fltType", 4 }, { "cutoff", 1200 }, { "fltEnv", 0 }, { "subOn", 1 }, { "subOct", 0 }, { "subLevel", 0.5f },
            { "distType", 0 }, { "distDrive", 0.5f }, { "distMix", 0.8f } }), mPoly),
        P ("Fold Throat", "Experimental", with (poly, { { "mode", 1 }, { "aTable", 6 }, { "aPos", 0.4f }, { "aWarp", 3 }, { "aWarpAmt", 0.5f }, { "ampS", 1.0f },
            { "fltType", 7 }, { "cutoff", 600 }, { "res", 0.5f }, { "fltEnv", 0 },
            { "lfo1Sync", 11 }, { "mod5Src", 1 }, { "mod5Dest", 8 }, { "mod5Amt", 0.6f }, { "mod6Src", 1 }, { "mod6Dest", 3 }, { "mod6Amt", 0.3f },
            { "subOn", 1 }, { "subOct", 0 }, { "subLevel", 0.5f }, { "distType", 2 }, { "distDrive", 0.3f }, { "distMix", 0.5f } }), mPoly),
        P ("Braaam Colossus", "Experimental", with (poly, { { "chord", 3 }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 5 }, { "aDetune", 0.15f },
            { "bOn", 1 }, { "bTable", 0 }, { "bPos", 0.66f }, { "bOct", -1 }, { "bUni", 3 }, { "subOn", 1 }, { "subLevel", 0.5f },
            { "dropAmt", 2 }, { "dropTime", 0.3f }, { "fltType", 1 }, { "cutoff", 300 }, { "fltEnv", 0.5f },
            { "modA", 0.4f }, { "modD", 2.0f }, { "modS", 0.4f }, { "ampA", 0.05f }, { "ampD", 4.0f }, { "ampS", 0.6f }, { "ampR", 2.0f },
            { "distType", 0 }, { "distDrive", 0.55f }, { "distMix", 0.9f }, { "verbMix", 0.4f }, { "verbSize", 0.9f } }), mPoly),
        P ("Event Horizon Riser", "Experimental", with (poly, { { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "noiseLevel", 0.4f },
            { "ampA", 0.5f }, { "ampS", 1.0f }, { "ampR", 2.0f }, { "fltType", 1 }, { "cutoff", 300 }, { "fltEnv", 0.7f },
            { "modA", 5.0f }, { "modS", 1.0f }, { "modR", 2.0f },
            { "mod5Src", 3 }, { "mod5Dest", 7 }, { "mod5Amt", 1.0f }, { "mod6Src", 3 }, { "mod6Dest", 13 }, { "mod6Amt", 0.5f },
            { "mod7Src", 3 }, { "mod7Dest", 17 }, { "mod7Amt", 0.8f }, { "lfo1Rate", 2.0f }, { "mod8Src", 1 }, { "mod8Dest", 8 }, { "mod8Amt", 0.15f },
            { "verbMix", 0.4f }, { "verbSize", 0.9f } }), mPoly),
        P ("Black Hole Impact", "Experimental", with (drum, { { "aTable", 12 }, { "aPos", 0 }, { "aOct", -1 }, { "dropAmt", 36 }, { "dropTime", 1.0f },
            { "noiseLevel", 0.5f }, { "noiseTone", 0.5f }, { "modD", 0.15f }, { "mod3Src", 3 }, { "mod3Dest", 12 }, { "mod3Amt", 0.8f },
            { "ampD", 4.0f }, { "ampR", 3.0f }, { "fltOn", 0 }, { "distType", 0 }, { "distDrive", 0.4f }, { "distMix", 0.8f },
            { "verbSize", 0.95f }, { "verbMix", 0.45f } }), mDrum),
        P ("Reverse Swell", "Experimental", with (poly, { { "aTable", 13 }, { "aPos", 0.5f }, { "aUni", 5 }, { "ampA", 1.8f }, { "ampS", 1.0f }, { "ampR", 0.1f },
            { "fltType", 2 }, { "cutoff", 4000 }, { "fltEnv", 0 }, { "modA", 1.8f }, { "modS", 1.0f },
            { "mod5Src", 3 }, { "mod5Dest", 8 }, { "mod5Amt", -0.8f }, { "verbShimmer", 0.5f }, { "verbMix", 0.5f } }), mPoly),
        P ("Dying Cassette", "Experimental", with (poly, { { "aTable", 12 }, { "aPos", 0.3f }, { "aUni", 3 }, { "aDetune", 0.06f },
            { "ampD", 1.5f }, { "ampS", 0.3f }, { "ampR", 0.5f }, { "fltType", 0 }, { "cutoff", 3000 }, { "fltEnv", 0.1f },
            { "noiseLevel", 0.06f }, { "noiseTone", 0.5f }, { "noiseFilter", 0 },
            { "lfo1Rate", 0.3f }, { "lfo1Retrig", 0 }, { "mod5Src", 1 }, { "mod5Dest", 7 }, { "mod5Amt", 0.008f },
            { "lfo2Shape", 6 }, { "lfo2Rate", 0.05f }, { "lfo2Retrig", 0 }, { "mod6Src", 2 }, { "mod6Dest", 7 }, { "mod6Amt", 0.004f },
            { "distType", 5 }, { "distDrive", 0.15f }, { "distMix", 0.3f } }), mPoly),
        P ("Thrift Store Organ", "Experimental", with (poly, { { "aTable", 2 }, { "aPos", 0.2f }, { "bOn", 1 }, { "bTable", 12 }, { "bOct", 1 }, { "bLevel", 0.5f },
            { "drift", 0.7f }, { "aWarp", 5 }, { "aWarpAmt", 0.2f }, { "ampS", 1.0f }, { "ampR", 0.15f },
            { "fltType", 0 }, { "cutoff", 2500 }, { "fltEnv", 0 }, { "chorusMix", 0.5f } }), mPoly),
        P ("Water-Damaged Music Box", "Experimental", with (fm, { { "aOct", 1 }, { "bOct", 2 }, { "mod1Amt", 0.2f }, { "modD", 0.15f }, { "ampD", 1.8f },
            { "drift", 0.4f }, { "mod5Src", 11 }, { "mod5Dest", 7 }, { "mod5Amt", 0.004f },
            { "lfo1Rate", 0.4f }, { "lfo1Retrig", 0 }, { "mod6Src", 1 }, { "mod6Dest", 7 }, { "mod6Amt", 0.006f },
            { "dlyTime", 5 }, { "dlyFb", 0.35f }, { "dlyMix", 0.25f }, { "dlyTone", 0.3f } }), mFm),
        P ("Latex Snap", "Experimental", with (drum, { { "aTable", 12 }, { "aPos", 0 }, { "dropAmt", 48 }, { "dropTime", 0.025f }, { "ampD", 0.25f },
            { "fltOn", 0 }, { "distType", 1 }, { "distDrive", 0.5f }, { "distMix", 0.5f } }), mDrum),
        P ("Insect Kit", "Experimental", with (drum, { { "aTable", 10 }, { "aLevel", 0.3f }, { "noiseLevel", 0.8f }, { "noiseTone", 0.9f },
            { "fltType", 3 }, { "cutoff", 3000 }, { "res", 0.7f }, { "fltKey", 1.0f }, { "ampD", 0.08f },
            { "lfo1Rate", 25.0f }, { "mod3Src", 1 }, { "mod3Dest", 8 }, { "mod3Amt", 0.3f } }), mDrum),
        P ("Metal Tom", "Experimental", with (string, { { "res", 0.95f }, { "noiseTone", 0.8f }, { "dropAmt", 7 }, { "dropTime", 0.05f }, { "ampD", 0.8f },
            { "distType", 1 }, { "distDrive", 0.3f }, { "distMix", 0.5f } }), mString),
        P ("Laser Hat", "Experimental", with (drum, { { "aTable", 7 }, { "aPos", 0.8f }, { "aOct", 3 }, { "dropAmt", 24 }, { "dropTime", 0.01f },
            { "noiseLevel", 0.3f }, { "noiseTone", 1.0f }, { "fltType", 2 }, { "cutoff", 6000 }, { "ampD", 0.06f } }), mDrum),
        P ("Candy Glass Lead", "Experimental", with (poly, { { "mode", 2 }, { "glide", 0.06f }, { "aTable", 7 }, { "aPos", 0.5f }, { "aWarp", 5 }, { "aWarpAmt", 0.15f },
            { "aUni", 7 }, { "aDetune", 0.3f }, { "ampS", 1.0f }, { "dropAmt", 12 }, { "dropTime", 0.015f }, { "fltOn", 0 },
            { "lfo2Rate", 5.5f }, { "lfo2Fade", 0.5f }, { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.01f },
            { "chorusMix", 0.3f }, { "dlyPing", 1 }, { "dlyTime", 4 }, { "dlyMix", 0.2f } }), mPoly),
        P ("Bubblegum Chainsaw", "Experimental", with (poly, { { "mode", 2 }, { "glide", 0.05f }, { "aTable", 0 }, { "aPos", 0.66f }, { "aUni", 7 }, { "aDetune", 0.35f },
            { "aWarp", 2 }, { "aWarpAmt", 0.3f }, { "ampS", 1.0f }, { "dropAmt", -5 }, { "dropTime", 0.08f },
            { "fltType", 1 }, { "cutoff", 7000 }, { "fltEnv", 0 },
            { "lfo2Rate", 6.0f }, { "lfo2Fade", 0.6f }, { "mod5Src", 2 }, { "mod5Dest", 7 }, { "mod5Amt", 0.01f },
            { "distType", 1 }, { "distDrive", 0.6f }, { "distMix", 0.7f } }), mPoly),
        P ("Slide Bell", "Experimental", with (fm, { { "mode", 2 }, { "glide", 0.12f }, { "bOct", 1 }, { "bSemi", 10 }, { "bFine", -31 },
            { "mod1Amt", 0.3f }, { "modD", 0.6f }, { "ampD", 3.0f }, { "ampS", 0.2f }, { "verbMix", 0.3f } }), mFm),
        P ("Bounce Squeak", "Experimental", with (poly, { { "mode", 1 }, { "glide", 0.04f }, { "aTable", 6 }, { "aPos", 0.4f },
            { "dropAmt", 12 }, { "dropTime", 0.06f }, { "ampD", 0.18f }, { "ampS", 0 },
            { "fltType", 7 }, { "cutoff", 1500 }, { "res", 0.4f } }), mPoly),
        P ("Eerie Drill Pad", "Experimental", with (pad, { { "chord", 15 }, { "aTable", 12 }, { "aPos", 0.4f }, { "aUni", 5 }, { "aDetune", 0.18f },
            { "fltType", 2 }, { "cutoff", 250 }, { "lfo1Rate", 0.1f }, { "mod1Dest", 13 }, { "mod1Amt", 0.3f }, { "chorusMix", 0.4f } }), mPad),
        P ("Glass Harp", "Experimental", with (string, { { "res", 0.993f }, { "noiseTone", 1.0f }, { "aOn", 1 }, { "aTable", 13 }, { "aLevel", 0.08f },
            { "ampD", 4.0f }, { "verbShimmer", 0.3f }, { "verbMix", 0.35f } }), mString),
        //================================================================ Club studies (0.6)
        // Appended, so existing host program numbers stay fixed. Dub, UK garage, house, baile funk and
        // club percussion/experimental. Macros: OPEN (GRIT on percussion), COLOUR, ECHO, SPACE.
        P ("Pressure Vessel", "Dub & Dancehall", with (clubBass, { { "aPos", 0.03f }, { "cutoff", 280.0f }, { "ampD", 1.3f }, { "ampS", 0.75f }, { "dropAmt", 7.0f }, { "dropTime", 0.012f }, { "subLevel", 0.48f } }), mClub),
        P ("Concrete Echo", "Dub & Dancehall", with (clubStab, { { "aTable", 2.0f }, { "aPos", 0.28f }, { "cutoff", 820.0f }, { "fltEnv", 0.4f }, { "dlyTime", 8.0f }, { "dlyFb", 0.48f }, { "dlyMix", 0.25f }, { "verbMode", 2.0f }, { "verbMix", 0.18f } }), mClub),
        P ("Submerged Organ", "Dub & Dancehall", with (clubStab, { { "aTable", 9.0f }, { "aPos", 0.18f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bOct", 1.0f }, { "bLevel", 0.22f }, { "chord", 11.0f }, { "cutoff", 1700.0f }, { "tapeWow", 0.12f }, { "tapeSat", 0.2f } }), mClub),
        P ("Cable Hum", "Dub & Dancehall", with (clubBass, { { "aTable", 0.0f }, { "aPos", 0.38f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bFine", 6.0f }, { "bLevel", 0.25f }, { "cutoff", 430.0f }, { "drift", 0.16f }, { "distMix", 0.38f } }), mClub),
        P ("Rust Chamber", "Dub & Dancehall", with (clubHit, { { "aTable", 10.0f }, { "aPos", 0.22f }, { "dropAmt", 0.0f }, { "ampD", 0.46f }, { "fltType", 6.0f }, { "cutoff", 320.0f }, { "res", 0.68f }, { "verbMode", 2.0f }, { "verbMix", 0.3f }, { "dlyMix", 0.18f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Drowned Reed", "Dub & Dancehall", with (club, { { "aTable", 6.0f }, { "aPos", 0.25f }, { "mode", 1.0f }, { "fltType", 7.0f }, { "cutoff", 540.0f }, { "res", 0.38f }, { "ampD", 0.6f }, { "ampS", 0.55f }, { "tapeWow", 0.13f }, { "dlyTime", 8.0f }, { "dlyMix", 0.2f } }), mClub),
        P ("Return Current", "Dub & Dancehall", with (clubAir, { { "aTable", 9.0f }, { "aPos", 0.15f }, { "fltType", 2.0f }, { "cutoff", 380.0f }, { "tapeWow", 0.18f }, { "tapeSat", 0.2f }, { "dlyStyle", 1.0f }, { "dlyMix", 0.25f } }), mClub),
        P ("Dry Dock", "Dub & Dancehall", with (clubBass, { { "aTable", 2.0f }, { "aPos", 0.08f }, { "ampD", 0.24f }, { "ampS", 0.0f }, { "ampR", 0.07f }, { "cutoff", 540.0f }, { "fltEnv", 0.18f }, { "distType", 3.0f }, { "distMix", 0.25f } }), mClub),
        P ("Hollow Exchange", "UK Garage", with (clubBass, { { "aTable", 2.0f }, { "aPos", 0.12f }, { "cutoff", 1100.0f }, { "fltEnv", 0.4f }, { "modD", 0.1f }, { "ampD", 0.32f }, { "ampS", 0.1f }, { "subLevel", 0.35f } }), mClub),
        P ("Elastic Tooth", "UK Garage", with (clubBass, { { "aWarp", 6.0f }, { "aWarpAmt", 0.045f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.0f }, { "bOct", 1.0f }, { "bLevel", 0.001f }, { "mod5Src", 3.0f }, { "mod5Dest", 3.0f }, { "mod5Amt", 0.42f }, { "ampD", 0.25f }, { "ampS", 0.1f }, { "fltOn", 0.0f } }), mClub),
        P ("Pocket Organ", "UK Garage", with (clubStab, { { "aTable", 9.0f }, { "aPos", 0.08f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bOct", 1.0f }, { "bLevel", 0.18f }, { "ampD", 0.19f }, { "ampR", 0.09f }, { "chord", 9.0f }, { "cutoff", 3400.0f }, { "chorusMix", 0.08f } }), mClub),
        P ("Late Connection", "UK Garage", with (club, { { "aTable", 12.0f }, { "aPos", 0.2f }, { "aWarp", 6.0f }, { "aWarpAmt", 0.035f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.0f }, { "bOct", 2.0f }, { "bLevel", 0.001f }, { "mod5Src", 3.0f }, { "mod5Dest", 3.0f }, { "mod5Amt", 0.3f }, { "ampD", 1.1f }, { "ampS", 0.0f }, { "chorusMix", 0.2f }, { "cutoff", 5000.0f } }), mClub),
        P ("Rubber Stamp", "UK Garage", with (clubBass, { { "aTable", 5.0f }, { "aPos", 0.13f }, { "fltType", 3.0f }, { "cutoff", 720.0f }, { "res", 0.32f }, { "fltEnv", 0.4f }, { "modD", 0.085f }, { "ampD", 0.2f }, { "ampS", 0.0f }, { "subLevel", 0.4f } }), mClub),
        P ("Glass Pager", "UK Garage", with (clubHit, { { "aTable", 13.0f }, { "aPos", 0.5f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bOct", 2.0f }, { "bLevel", 0.12f }, { "xRing", 0.25f }, { "dropAmt", 0.0f }, { "ampD", 0.35f }, { "dlyTime", 3.0f }, { "dlyMix", 0.13f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Velvet Choke", "UK Garage", with (clubStab, { { "aTable", 6.0f }, { "aPos", 0.28f }, { "fltType", 7.0f }, { "cutoff", 950.0f }, { "res", 0.32f }, { "ampD", 0.15f }, { "ampR", 0.07f }, { "chord", 11.0f }, { "dlyMix", 0.08f } }), mClub),
        P ("Side Street", "UK Garage", with (clubBass, { { "aTable", 0.0f }, { "aPos", 0.6f }, { "aUni", 2.0f }, { "aDetune", 0.09f }, { "cutoff", 950.0f }, { "fltEnv", 0.3f }, { "ampD", 0.42f }, { "ampS", 0.3f }, { "subLevel", 0.42f }, { "glide", 0.025f } }), mClub),
        P ("Dust Circuit", "House Stabs", with (clubStab, { { "aTable", 0.0f }, { "aPos", 0.67f }, { "cutoff", 1300.0f }, { "chord", 14.0f }, { "tapeSat", 0.26f }, { "tapeWow", 0.08f }, { "verbMode", 3.0f } }), mClub),
        P ("Blue Hour Keys", "House Stabs", with (club, { { "aTable", 12.0f }, { "aPos", 0.2f }, { "aWarp", 6.0f }, { "aWarpAmt", 0.025f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.0f }, { "bOct", 1.0f }, { "bLevel", 0.001f }, { "mod5Src", 3.0f }, { "mod5Dest", 3.0f }, { "mod5Amt", 0.22f }, { "ampD", 1.5f }, { "ampS", 0.05f }, { "cutoff", 6000.0f }, { "chorusMode", 2.0f }, { "chorusMix", 0.28f } }), mClub),
        P ("Wire Blossom", "House Stabs", with (clubStab, { { "aTable", 13.0f }, { "aPos", 0.35f }, { "chord", 12.0f }, { "ampD", 0.6f }, { "cutoff", 2700.0f }, { "verbMix", 0.2f }, { "verbShimmer", 0.1f } }), mClub),
        P ("Soft Machinery", "House Bass", with (clubBass, { { "aTable", 0.0f }, { "aPos", 0.5f }, { "cutoff", 630.0f }, { "fltEnv", 0.25f }, { "modD", 0.16f }, { "ampD", 0.3f }, { "ampS", 0.12f }, { "subLevel", 0.3f }, { "tapeSat", 0.15f } }), mClub),
        P ("Pressed Wax", "House Stabs", with (clubStab, { { "aTable", 2.0f }, { "aPos", 0.25f }, { "chord", 10.0f }, { "fltType", 0.0f }, { "cutoff", 1700.0f }, { "distType", 5.0f }, { "distDrive", 0.1f }, { "distMix", 0.15f }, { "tapeWow", 0.06f } }), mClub),
        P ("Open Shutters", "House Stabs", with (club, { { "aTable", 9.0f }, { "aPos", 0.45f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.5f }, { "bOct", 1.0f }, { "bLevel", 0.14f }, { "ampD", 0.8f }, { "ampS", 0.2f }, { "cutoff", 3600.0f }, { "chorusMix", 0.3f }, { "fltEnv", 0.2f } }), mClub),
        P ("Pinhole Acid", "House Bass", with (clubBass, { { "aTable", 0.0f }, { "aPos", 0.65f }, { "cutoff", 450.0f }, { "res", 0.65f }, { "fltEnv", 0.65f }, { "modD", 0.12f }, { "ampD", 0.2f }, { "ampS", 0.1f }, { "subLevel", 0.15f }, { "distDrive", 0.3f }, { "distMix", 0.3f } }), mClub),
        P ("Empty Room Chord", "House Stabs", with (clubStab, { { "aTable", 12.0f }, { "aPos", 0.38f }, { "chord", 13.0f }, { "ampD", 0.48f }, { "cutoff", 2100.0f }, { "verbMode", 3.0f }, { "verbMix", 0.22f }, { "dlyMix", 0.08f } }), mClub),
        P ("Chrome Tambor", "Baile Funk", with (clubHit, { { "aWarp", 6.0f }, { "aWarpAmt", 0.09f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.0f }, { "bSemi", 7.0f }, { "bLevel", 0.001f }, { "mod5Src", 3.0f }, { "mod5Dest", 3.0f }, { "mod5Amt", 0.7f }, { "modD", 0.028f }, { "dropAmt", 19.0f }, { "ampD", 0.18f }, { "distType", 3.0f }, { "distMix", 0.4f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Wire Whistle", "Baile Funk", with (club, { { "aTable", 12.0f }, { "aPos", 0.01f }, { "aOct", 2.0f }, { "mode", 1.0f }, { "ampD", 0.16f }, { "ampS", 0.35f }, { "ampR", 0.035f }, { "dropAmt", -5.0f }, { "dropTime", 0.025f }, { "fltOn", 0.0f }, { "lfo1Rate", 7.0f }, { "mod5Src", 1.0f }, { "mod5Dest", 7.0f }, { "mod5Amt", 0.012f } }), mClub),
        P ("Piston Knock", "Baile Funk", with (clubHit, { { "aTable", 3.0f }, { "aPos", 0.08f }, { "dropAmt", 36.0f }, { "dropTime", 0.015f }, { "ampD", 0.22f }, { "distType", 3.0f }, { "distDrive", 0.42f }, { "distMix", 0.65f }, { "subOn", 1.0f }, { "subOct", 0.0f }, { "subLevel", 0.18f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Razor Reed", "Baile Funk", with (club, { { "aTable", 2.0f }, { "aPos", 0.35f }, { "aWarp", 4.0f }, { "aWarpAmt", 0.35f }, { "mode", 1.0f }, { "ampD", 0.2f }, { "ampS", 0.4f }, { "ampR", 0.035f }, { "fltType", 3.0f }, { "cutoff", 1800.0f }, { "res", 0.25f }, { "distType", 1.0f }, { "distMix", 0.25f } }), mClub),
        P ("Steel Tongue", "Baile Funk", with (clubHit, { { "aTable", 10.0f }, { "aPos", 0.32f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bSemi", 6.0f }, { "bLevel", 0.25f }, { "xRing", 0.45f }, { "dropAmt", 7.0f }, { "ampD", 0.12f }, { "cutoff", 4500.0f }, { "distMix", 0.2f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Bent Horn", "Baile Funk", with (club, { { "aTable", 0.0f }, { "aPos", 0.66f }, { "bOn", 1.0f }, { "bTable", 2.0f }, { "bSemi", 7.0f }, { "bLevel", 0.18f }, { "mode", 1.0f }, { "dropAmt", -12.0f }, { "dropTime", 0.04f }, { "ampD", 0.28f }, { "ampS", 0.1f }, { "fltType", 7.0f }, { "cutoff", 1700.0f }, { "res", 0.4f } }), mClub),
        P ("Concrete Slap", "Baile Funk", with (clubHit, { { "ott", 0.45f }, { "aLevel", 0.3f }, { "noiseLevel", 1.0f }, { "noiseTone", 0.82f }, { "noiseType", 0.0f }, { "fltType", 3.0f }, { "cutoff", 2200.0f }, { "res", 0.2f }, { "dropAmt", 0.0f }, { "ampD", 0.2f }, { "distType", 1.0f }, { "distMix", 0.35f }, { "verbMode", 3.0f }, { "verbMix", 0.12f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Torn Cone", "Baile Funk", with (clubBass, { { "aTable", 3.0f }, { "aPos", 0.28f }, { "dropAmt", 19.0f }, { "dropTime", 0.022f }, { "ampD", 0.42f }, { "ampS", 0.0f }, { "cutoff", 3800.0f }, { "distType", 3.0f }, { "distDrive", 0.55f }, { "distMix", 0.75f }, { "subLevel", 0.26f } }), mClub),
        P ("Broken Ceramic", "Club Percussion", with (clubHit, { { "ott", 0.4f }, { "distType", 1.0f }, { "distDrive", 0.35f }, { "distMix", 0.4f }, { "aTable", 13.0f }, { "aPos", 0.6f }, { "xRing", 0.6f }, { "bOn", 1.0f }, { "bTable", 10.0f }, { "bSemi", 6.0f }, { "bLevel", 0.12f }, { "dropAmt", 0.0f }, { "ampD", 0.12f }, { "aLevel", 1.0f }, { "fltType", 2.0f }, { "cutoff", 2400.0f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Pressure Rim", "Club Percussion", with (clubHit, { { "ott", 0.4f }, { "aTable", 12.0f }, { "aPos", 0.05f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.0f }, { "bSemi", 11.0f }, { "bLevel", 0.001f }, { "aWarp", 6.0f }, { "aWarpAmt", 0.65f }, { "ampD", 0.1f }, { "aLevel", 1.0f }, { "dropAmt", 0.0f }, { "fltType", 3.0f }, { "cutoff", 1500.0f }, { "res", 0.4f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Foil Shaker", "Club Percussion", with (clubHit, { { "ott", 0.45f }, { "aOn", 0.0f }, { "noiseLevel", 1.0f }, { "noiseTone", 1.0f }, { "noiseType", 3.0f }, { "fltType", 2.0f }, { "cutoff", 5500.0f }, { "ampD", 0.09f }, { "dropAmt", 0.0f }, { "distType", 5.0f }, { "distMix", 0.12f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Drainpipe Tom", "Club Percussion", with (clubHit, { { "aTable", 12.0f }, { "aPos", 0.14f }, { "dropAmt", 12.0f }, { "dropTime", 0.035f }, { "fltType", 6.0f }, { "cutoff", 240.0f }, { "res", 0.73f }, { "ampD", 0.28f }, { "verbMode", 3.0f }, { "verbMix", 0.12f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Magnet Clave", "Club Percussion", with (clubHit, { { "ott", 0.5f }, { "distType", 1.0f }, { "distDrive", 0.4f }, { "distMix", 0.5f }, { "aTable", 10.0f }, { "aPos", 0.1f }, { "dropAmt", 3.0f }, { "dropTime", 0.008f }, { "ampD", 0.08f }, { "aLevel", 1.0f }, { "fltType", 3.0f }, { "cutoff", 2800.0f }, { "res", 0.55f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Paper Kick", "Club Percussion", with (clubHit, { { "aTable", 3.0f }, { "aPos", 0.01f }, { "aOct", -1.0f }, { "dropAmt", 30.0f }, { "dropTime", 0.028f }, { "ampD", 0.32f }, { "noiseLevel", 0.02f }, { "noiseTone", 0.7f }, { "distType", 3.0f }, { "distMix", 0.3f }, { "cutoff", 5500.0f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Ceramic Bell", "Club Percussion", with (clubHit, { { "aTable", 12.0f }, { "aWarp", 6.0f }, { "aWarpAmt", 0.2f }, { "bOn", 1.0f }, { "bTable", 0.0f }, { "bPos", 0.0f }, { "bOct", 2.0f }, { "bSemi", 3.0f }, { "bLevel", 0.001f }, { "dropAmt", 0.0f }, { "ampD", 0.5f }, { "mod5Src", 3.0f }, { "mod5Dest", 3.0f }, { "mod5Amt", 0.25f }, { "modD", 0.045f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Scraped Alloy", "Club Percussion", with (clubHit, { { "aTable", 10.0f }, { "aPos", 0.45f }, { "noiseLevel", 0.3f }, { "noiseType", 6.0f }, { "fltType", 2.0f }, { "cutoff", 2200.0f }, { "ampA", 0.015f }, { "ampD", 0.22f }, { "dropAmt", -7.0f }, { "dropTime", 0.12f }, { "flangMix", 0.2f }, { "flangFb", 0.35f } }), Macros { "GRIT", "COLOUR", "ECHO", "SPACE" }),
        P ("Liquid Relay", "Club Experimental", with (clubBass, { { "aTable", 6.0f }, { "aPos", 0.3f }, { "fltType", 7.0f }, { "cutoff", 740.0f }, { "res", 0.4f }, { "lfo1Rate", 3.1f }, { "mod5Src", 1.0f }, { "mod5Dest", 8.0f }, { "mod5Amt", 0.25f }, { "xFmBA", 0.15f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bLevel", 0.1f }, { "subLevel", 0.35f } }), mClub),
        P ("Hollow Hologram", "Club Experimental", with (clubAir, { { "aTable", 13.0f }, { "aPos", 0.45f }, { "fltType", 6.0f }, { "cutoff", 520.0f }, { "res", 0.72f }, { "ampA", 0.03f }, { "ampD", 1.2f }, { "ampS", 0.25f }, { "shiftMix", 0.18f }, { "shiftSemis", 7.0f } }), mClub),
        P ("Melted Dialtone", "Club Experimental", with (club, { { "aTable", 12.0f }, { "aPos", 0.06f }, { "bOn", 1.0f }, { "bTable", 12.0f }, { "bSemi", 6.0f }, { "bLevel", 0.3f }, { "xRing", 0.32f }, { "mode", 1.0f }, { "glide", 0.15f }, { "fltType", 3.0f }, { "cutoff", 1500.0f }, { "res", 0.3f }, { "dlyStyle", 1.0f }, { "dlyMix", 0.23f } }), mClub),
        P ("Breathing Plastic", "Club Experimental", with (clubAir, { { "aTable", 6.0f }, { "aPos", 0.2f }, { "fltType", 7.0f }, { "cutoff", 1100.0f }, { "res", 0.3f }, { "lfo1Rate", 0.38f }, { "mod5Dest", 8.0f }, { "mod5Amt", 0.3f }, { "noiseLevel", 0.025f }, { "noiseType", 1.0f } }), mClub),
        P ("Fracture Bloom", "Club Experimental", with (clubStab, { { "aTable", 7.0f }, { "aPos", 0.5f }, { "chord", 15.0f }, { "aWarp", 5.0f }, { "aWarpAmt", 0.16f }, { "ampD", 0.65f }, { "fltType", 4.0f }, { "cutoff", 2400.0f }, { "verbShimmer", 0.22f }, { "dlyStyle", 2.0f }, { "dlyMix", 0.2f } }), mClub),
        P ("Ghost Carrier", "Club Experimental", with (clubAir, { { "aTable", 12.0f }, { "aPos", 0.08f }, { "bOn", 1.0f }, { "bTable", 14.0f }, { "bLevel", 0.08f }, { "bOct", 1.0f }, { "xFmBA", 0.09f }, { "fltType", 2.0f }, { "cutoff", 420.0f }, { "chorusMode", 2.0f }, { "chorusMix", 0.35f }, { "verbShimmer", 0.15f } }), mClub),
        P ("Folded Rubber", "Club Experimental", with (clubBass, { { "aTable", 8.0f }, { "aPos", 0.24f }, { "aWarp", 2.0f }, { "aWarpAmt", 0.16f }, { "fltType", 4.0f }, { "cutoff", 900.0f }, { "dropAmt", -7.0f }, { "dropTime", 0.055f }, { "ampD", 0.32f }, { "ampS", 0.2f }, { "distType", 2.0f }, { "distMix", 0.3f }, { "subLevel", 0.4f } }), mClub),
        P ("Afterimage Dust", "Club Experimental", with (clubAir, { { "aTable", 14.0f }, { "aPos", 0.6f }, { "noiseLevel", 0.035f }, { "noiseType", 4.0f }, { "fltType", 2.0f }, { "cutoff", 650.0f }, { "tapeWow", 0.2f }, { "tapeSat", 0.2f }, { "dlyStyle", 1.0f }, { "dlyFb", 0.4f }, { "dlyMix", 0.22f }, { "ampA", 0.6f }, { "ampR", 2.2f } }), mClub),
        // Donk & Bounce (appended: earlier program numbers stay put).
        P ("Scouse Donk", "Donk & Bounce", donk, mDonk),
        P ("Bamboo Donk", "Donk & Bounce", with (donk, { { "bPos", 0.33f }, { "bOct", 1.0f }, { "bSemi", 7.0f }, { "aWarpAmt", 0.04f },
            { "mod1Amt", 0.3f }, { "modD", 0.05f }, { "ampD", 0.2f }, { "dropAmt", 5.0f }, { "cutoff", 3600.0f } }), mDonk),
        P ("Hard House Donk", "Donk & Bounce", with (donk, { { "mod1Amt", 0.48f }, { "aWarpAmt", 0.09f }, { "ampD", 0.18f }, { "dropAmt", 7.0f },
            { "dropTime", 0.012f }, { "cutoff", 6000.0f }, { "distType", 1.0f }, { "distDrive", 0.35f }, { "distMix", 0.35f }, { "ott", 0.3f } }), mDonk),
        P ("Bounce Donk", "Donk & Bounce", with (donk, { { "ampD", 0.3f }, { "ampS", 0.08f }, { "modD", 0.1f }, { "mod1Amt", 0.36f },
            { "chorusMix", 0.18f }, { "chorusMode", 2.0f }, { "dlyTime", 5.0f }, { "dlyFb", 0.25f }, { "dlyMix", 0.12f }, { "dlyTone", 0.45f } }), mDonk),
        P ("Rubber Donk", "Donk & Bounce", with (donk, { { "aWarp", 0.0f }, { "aPos", 0.33f }, { "bLevel", 0.55f }, { "bFine", 9.0f }, { "bFilter", 1.0f },
            { "mod1Src", 3.0f }, { "mod1Dest", 8.0f }, { "mod1Amt", 0.45f }, { "mod2Dest", 8.0f }, { "mod2Amt", 0.3f },
            { "cutoff", 380.0f }, { "res", 0.72f }, { "modD", 0.11f }, { "ampD", 0.26f }, { "dropAmt", 4.0f } }), mDonk),
        P ("Gont", "Donk & Bounce", with (donk, { { "bLevel", 0.12f }, { "bFine", 6.0f }, { "bFilter", 1.0f }, { "mod1Amt", 0.4f },
            { "modD", 0.07f }, { "ampD", 0.22f }, { "cutoff", 3000.0f }, { "distMix", 0.3f } }), mDonk),
        P ("Donk Sub", "Donk & Bounce", with (donk, { { "subOn", 1.0f }, { "subOct", -1.0f }, { "subLevel", 0.38f }, { "subFilter", 0.0f },
            { "ampD", 0.28f }, { "mod1Amt", 0.34f }, { "cutoff", 3200.0f }, { "monoBass", 1.0f } }), mDonk),
        P ("Hardbass Donk", "Donk & Bounce", with (donk, { { "mod1Amt", 0.44f }, { "ampD", 0.26f }, { "ampS", 0.1f }, { "dropAmt", 10.0f },
            { "dropTime", 0.01f }, { "cutoff", 5000.0f }, { "distType", 3.0f }, { "distDrive", 0.5f }, { "distMix", 0.5f }, { "ott", 0.35f },
            { "subOn", 1.0f }, { "subOct", -1.0f }, { "subLevel", 0.25f } }), mDonk),
        P ("Pipe Donk", "Donk & Bounce", with (donk, { { "bOct", 1.0f }, { "aWarpAmt", 0.05f }, { "mod1Amt", 0.32f }, { "modD", 0.06f },
            { "fltType", 3.0f }, { "cutoff", 950.0f }, { "res", 0.35f }, { "fltMix", 0.6f }, { "ampD", 0.2f } }), mDonk),
        P ("Deep House Donk", "Donk & Bounce", with (donk, { { "mode", 0.0f }, { "mod1Amt", 0.22f }, { "aWarpAmt", 0.05f }, { "modD", 0.14f },
            { "ampD", 0.36f }, { "ampS", 0.12f }, { "ampR", 0.12f }, { "dropAmt", 3.0f }, { "dropTime", 0.02f }, { "cutoff", 1900.0f },
            { "distMix", 0.0f }, { "chorusMix", 0.15f }, { "verbMode", 1.0f }, { "verbMix", 0.12f } }), mDonk),
    };
}

} // namespace ab
